# **Projeto de Graduação em Computação II [2026-Q1]**

Universidade Federal do ABC

Orientador Carlos da Silva dos Santos

### **EQUIPE**

---

Caio Cardoso Dos Santos - RA: 11202021632

Victor Ravazio de Lima - RA: 11201920941

### **IMPLEMENTAÇÃO**
---

In [1]:
# modulo para importar dataset a partir de um link
!pip install gdown

Requirement already satisfied: gdown in /usr/local/lib/python3.12/dist-packages (5.2.1)
Requirement already satisfied: beautifulsoup4 in /usr/local/lib/python3.12/dist-packages (from gdown) (4.13.5)
Requirement already satisfied: filelock in /usr/local/lib/python3.12/dist-packages (from gdown) (3.25.2)
Requirement already satisfied: requests[socks] in /usr/local/lib/python3.12/dist-packages (from gdown) (2.32.4)
Requirement already satisfied: tqdm in /usr/local/lib/python3.12/dist-packages (from gdown) (4.67.3)
Requirement already satisfied: soupsieve>1.2 in /usr/local/lib/python3.12/dist-packages (from beautifulsoup4->gdown) (2.8.3)
Requirement already satisfied: typing-extensions>=4.0.0 in /usr/local/lib/python3.12/dist-packages (from beautifulsoup4->gdown) (4.15.0)
Requirement already satisfied: charset_normalizer<4,>=2 in /usr/local/lib/python3.12/dist-packages (from requests[socks]->gdown) (3.4.7)
Requirement already satisfied: idna<4,>=2.5 in /usr/local/lib/python3.12/dist-packages (from requests[socks]->gdown) (3.11)
Requirement already satisfied: urllib3<3,>=1.21.1 in /usr/local/lib/python3.12/dist-packages (from requests[socks]->gdown) (2.5.0)
Requirement already satisfied: certifi>=2017.4.17 in /usr/local/lib/python3.12/dist-packages (from requests[socks]->gdown) (2026.2.25)
Requirement already satisfied: PySocks!=1.5.7,>=1.5.6 in /usr/local/lib/python3.12/dist-packages (from requests[socks]->gdown) (1.7.1)

In [2]:
#Bibliotecas
import pandas as pd
import numpy as np
from google.colab import files
import gdown
import matplotlib.pyplot as plt
import random

In [3]:
# baixando dataset para o collab
import gdown

file_id = "1PPjaezcZu_asNyC93X6uj3kspJGW1q0F"
url = f"https://drive.google.com/uc?id={file_id}"

gdown.download(url, "mandetta.csv", quiet=False)

Downloading...
From: https://drive.google.com/uc?id=1PPjaezcZu_asNyC93X6uj3kspJGW1q0F
To: /content/mandetta.csv
100%|██████████| 21.0M/21.0M [00:00<00:00, 52.0MB/s]

'mandetta.csv'

In [4]:
#carregando o dataset
df = pd.read_csv ("mandetta.csv")
df.head()

/usr/local/lib/python3.12/dist-packages/google/colab/_dataframe_summarizer.py:88: UserWarning: Could not infer format, so each element will be parsed individually, falling back to `dateutil`. To ensure parsing is consistent and as-expected, please specify a format.
  cast_date_col = pd.to_datetime(column, errors="coerce")

,tweet_id,user_id_original,text,created_at_original,retweet_count,like_count,is_retweet,retweeter_user_id,retweet_created_at,is_quote,quoted_tweet_id,quoted_user_id,quoted_text,is_reply,reply_to_tweet_id,reply_to_user_id,reply_to_screen_name,reply_text,class
0,1250828250370183168,57664074,"Para quem defendia o Mandetta , agora já sabe ...",Thu Apr 16 16:47:48 +0000 2020,0,0,False,NaN,NaN,False,NaN,NaN,NaN,False,NaN,NaN,NaN,NaN,0
1,1250828253260132353,882627779363254274,que merdaaaaaaaaaaaaaa tiraram o mandetta véi,Thu Apr 16 16:47:49 +0000 2020,0,0,False,NaN,NaN,False,NaN,NaN,NaN,False,NaN,NaN,NaN,NaN,0
2,1250827965899984907,1164652265271189510,#estudioi Mandetta estava usando Bolsonaro com...,Thu Apr 16 16:46:40 +0000 2020,1,1,True,9.619537e+17,Thu Apr 16 16:47:49 +0000 2020,False,NaN,NaN,NaN,False,NaN,NaN,NaN,NaN,0
3,1250780916575866881,1138847289978626049,"Dória, Witzel, Alcolumbre, Rodrigo Maia, Mande...",Thu Apr 16 13:39:43 +0000 2020,751,2333,True,1.656291e+09,Thu Apr 16 16:47:49 +0000 2020,False,NaN,NaN,NaN,False,NaN,NaN,NaN,NaN,0
4,1250828255806009345,1039608133587554311,"Demorou, não deveria ne ter sido nomeado mande...",Thu Apr 16 16:47:50 +0000 2020,0,0,False,NaN,NaN,False,NaN,NaN,NaN,True,1.250553e+18,1.523748e+09,conexaopolitica,"“O dia que ele [Mandetta] sair, eu saio junto ...",1

In [5]:
#numero total de instancias no dataset
df.shape

(66236, 19)

In [6]:
df

/usr/local/lib/python3.12/dist-packages/google/colab/_dataframe_summarizer.py:88: UserWarning: Could not infer format, so each element will be parsed individually, falling back to `dateutil`. To ensure parsing is consistent and as-expected, please specify a format.
  cast_date_col = pd.to_datetime(column, errors="coerce")

,tweet_id,user_id_original,text,created_at_original,retweet_count,like_count,is_retweet,retweeter_user_id,retweet_created_at,is_quote,quoted_tweet_id,quoted_user_id,quoted_text,is_reply,reply_to_tweet_id,reply_to_user_id,reply_to_screen_name,reply_text,class
0,1250828250370183168,57664074,"Para quem defendia o Mandetta , agora já sabe ...",Thu Apr 16 16:47:48 +0000 2020,0,0,False,NaN,NaN,False,NaN,NaN,NaN,False,NaN,NaN,NaN,NaN,0
1,1250828253260132353,882627779363254274,que merdaaaaaaaaaaaaaa tiraram o mandetta véi,Thu Apr 16 16:47:49 +0000 2020,0,0,False,NaN,NaN,False,NaN,NaN,NaN,False,NaN,NaN,NaN,NaN,0
2,1250827965899984907,1164652265271189510,#estudioi Mandetta estava usando Bolsonaro com...,Thu Apr 16 16:46:40 +0000 2020,1,1,True,9.619537e+17,Thu Apr 16 16:47:49 +0000 2020,False,NaN,NaN,NaN,False,NaN,NaN,NaN,NaN,0
3,1250780916575866881,1138847289978626049,"Dória, Witzel, Alcolumbre, Rodrigo Maia, Mande...",Thu Apr 16 13:39:43 +0000 2020,751,2333,True,1.656291e+09,Thu Apr 16 16:47:49 +0000 2020,False,NaN,NaN,NaN,False,NaN,NaN,NaN,NaN,0
4,1250828255806009345,1039608133587554311,"Demorou, não deveria ne ter sido nomeado mande...",Thu Apr 16 16:47:50 +0000 2020,0,0,False,NaN,NaN,False,NaN,NaN,NaN,True,1.250553e+18,1.523748e+09,conexaopolitica,"“O dia que ele [Mandetta] sair, eu saio junto ...",1
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
66231,1251194009374031873,3145117967,Esse vídeo do Mandetta Abraçando e cantando ap...,Fri Apr 17 17:01:12 +0000 2020,0,0,False,NaN,NaN,False,NaN,NaN,NaN,True,1.251163e+18,1.597286e+08,bruno_rteixeira,NaN,1
66232,1251194013429968897,1185228960818499584,Mandetta se corrompeu a corrupção. VazaaaMandetta,Fri Apr 17 17:01:13 +0000 2020,0,0,False,NaN,NaN,False,NaN,NaN,NaN,False,NaN,NaN,NaN,NaN,0
66233,1251185636545085441,1022539297658953728,"O maior infectologista do mundo,Didier Raoult,...",Fri Apr 17 16:27:56 +0000 2020,5,18,True,7.159120e+17,Fri Apr 17 17:01:16 +0000 2020,False,NaN,NaN,NaN,False,NaN,NaN,NaN,NaN,0
66234,1251194027124408328,52720920,"Pra eles pode tudo Gil, só não pode o Presiden...",Fri Apr 17 17:01:16 +0000 2020,0,0,False,NaN,NaN,False,NaN,NaN,NaN,True,1.251191e+18,6.229100e+07,gilebruno,NaN,1
66235,1250893581453332483,58951368,Morre um ministro. Nasce um candidato?,Thu Apr 16 21:07:24 +0000 2020,803,14164,False,NaN,NaN,False,NaN,NaN,NaN,False,NaN,NaN,NaN,NaN,0

In [7]:
df[df['reply_text'].str.contains('eu vendo a #AbortoNAO subir e lembrando dessas', na=False)]

Empty DataFrame
Columns: [tweet_id, user_id_original, text, created_at_original, retweet_count, like_count, is_retweet, retweeter_user_id, retweet_created_at, is_quote, quoted_tweet_id, quoted_user_id, quoted_text, is_reply, reply_to_tweet_id, reply_to_user_id, reply_to_screen_name, reply_text, class]
Index: []

In [8]:
#classe 0
sum_class_0 = int ((df['class'] == 0).sum())
sum_class_0

25625

In [9]:
#Classe 1
sum_class_1 = int ((df['class'] == 1).sum())
sum_class_1

19732

In [10]:
#classe 2
sum_class_2 = int ((df['class'] == 2).sum())
sum_class_2

20879

In [11]:
#numero de tweets genericos (não é quote nem reply)
generics = df.loc[(df["is_quote"] == False) & (df["is_reply"] == False)]
generics.shape[0]

25625

In [12]:
#numero de tweets replys totais (com e sem respostas os respectivos tweets originais obtidos)
replys_tot = df.loc[df["is_reply"] == True]
replys_tot.shape[0]

20012

In [13]:
#numero de tweets replys com respostas encontradas
replys = df.loc[(df["is_reply"]) & (df["reply_text"].notna())]
replys.shape[0]

6479

In [14]:
#numero de quotes
quoteds_tot = df.loc[df["is_quote"] == True]
quoteds_tot.shape[0]

20879

In [15]:
#numero de quotes usaveis
quoteds = df.loc[(df["is_quote"] == True) & (df["quoted_text"].notna())]
quoteds.shape[0]

20800

In [16]:
#intersecções entre quotes e replys
replys_quotes = df.loc[(df["is_reply"] == True) & (df["is_quote"] == True)]
replys_quotes.shape[0]

280

In [17]:
tot = generics.shape[0] + replys_tot.shape[0] + quoteds_tot.shape[0] - replys_quotes.shape[0]
tot

66236

In [18]:
replys_tot.head()

,tweet_id,user_id_original,text,created_at_original,retweet_count,like_count,is_retweet,retweeter_user_id,retweet_created_at,is_quote,quoted_tweet_id,quoted_user_id,quoted_text,is_reply,reply_to_tweet_id,reply_to_user_id,reply_to_screen_name,reply_text,class
4,1250828255806009345,1039608133587554311,"Demorou, não deveria ne ter sido nomeado mande...",Thu Apr 16 16:47:50 +0000 2020,0,0,False,NaN,NaN,False,NaN,NaN,NaN,True,1.250553e+18,1.523748e+09,conexaopolitica,"“O dia que ele [Mandetta] sair, eu saio junto ...",1
12,1250828263938830337,914939873781600261,Mandetta subiu no palanque e continua se achan...,Thu Apr 16 16:47:52 +0000 2020,0,0,False,NaN,NaN,False,NaN,NaN,NaN,True,1.250556e+18,1.250408e+18,Rodrigo96884079,NaN,1
13,1250828263976558593,170400715,"Como uma cobra ratoeira, está o senhor senador...",Thu Apr 16 16:47:52 +0000 2020,0,0,False,NaN,NaN,False,NaN,NaN,NaN,True,1.250796e+18,7.374596e+07,alvarodias_,A maioria esmagadora dos brasileiros é contrár...,1
18,1250821578318897156,35219319,#ForaMandettaTraira Eu não fui entrevistada!...,Thu Apr 16 16:21:18 +0000 2020,12,23,True,3.127892e+09,Thu Apr 16 16:47:55 +0000 2020,False,NaN,NaN,NaN,True,1.250796e+18,7.374596e+07,alvarodias_,A maioria esmagadora dos brasileiros é contrár...,1
32,1250828326454923267,1095129896630841345,Mandetta é um TRAIDOR!!!! #ForaMandettaUrgente,Thu Apr 16 16:48:06 +0000 2020,0,0,False,NaN,NaN,False,NaN,NaN,NaN,True,1.250783e+18,3.352020e+07,Rconstantino,Mandetta e sua política de isolamento estão lo...,1

# **Pares Tweets genéricos**

In [19]:
generics = df.loc[(df["is_quote"] == False) & (df["is_reply"] == False)]
generics

/usr/local/lib/python3.12/dist-packages/google/colab/_dataframe_summarizer.py:88: UserWarning: Could not infer format, so each element will be parsed individually, falling back to `dateutil`. To ensure parsing is consistent and as-expected, please specify a format.
  cast_date_col = pd.to_datetime(column, errors="coerce")

,tweet_id,user_id_original,text,created_at_original,retweet_count,like_count,is_retweet,retweeter_user_id,retweet_created_at,is_quote,quoted_tweet_id,quoted_user_id,quoted_text,is_reply,reply_to_tweet_id,reply_to_user_id,reply_to_screen_name,reply_text,class
0,1250828250370183168,57664074,"Para quem defendia o Mandetta , agora já sabe ...",Thu Apr 16 16:47:48 +0000 2020,0,0,False,NaN,NaN,False,NaN,NaN,NaN,False,NaN,NaN,NaN,NaN,0
1,1250828253260132353,882627779363254274,que merdaaaaaaaaaaaaaa tiraram o mandetta véi,Thu Apr 16 16:47:49 +0000 2020,0,0,False,NaN,NaN,False,NaN,NaN,NaN,False,NaN,NaN,NaN,NaN,0
2,1250827965899984907,1164652265271189510,#estudioi Mandetta estava usando Bolsonaro com...,Thu Apr 16 16:46:40 +0000 2020,1,1,True,9.619537e+17,Thu Apr 16 16:47:49 +0000 2020,False,NaN,NaN,NaN,False,NaN,NaN,NaN,NaN,0
3,1250780916575866881,1138847289978626049,"Dória, Witzel, Alcolumbre, Rodrigo Maia, Mande...",Thu Apr 16 13:39:43 +0000 2020,751,2333,True,1.656291e+09,Thu Apr 16 16:47:49 +0000 2020,False,NaN,NaN,NaN,False,NaN,NaN,NaN,NaN,0
5,1250817185154510848,1045860705130467328,"Falaram hoje que, trocar o MANDETTA por outro ...",Thu Apr 16 16:03:50 +0000 2020,3,4,True,8.729373e+17,Thu Apr 16 16:47:50 +0000 2020,False,NaN,NaN,NaN,False,NaN,NaN,NaN,NaN,0
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
66227,1251193995360972802,1058806309754146817,A MÁSCARA DO MANDETTA CAIU: Gozado! Agora que ...,Fri Apr 17 17:01:09 +0000 2020,0,0,False,NaN,NaN,False,NaN,NaN,NaN,False,NaN,NaN,NaN,NaN,0
66229,1251192931857432579,3254069824,Mandetta; Ñ apertem as mãos Ñ se aglmerem. Ñ S...,Fri Apr 17 16:56:55 +0000 2020,13,19,True,1.221462e+18,Fri Apr 17 17:01:11 +0000 2020,False,NaN,NaN,NaN,False,NaN,NaN,NaN,NaN,0
66232,1251194013429968897,1185228960818499584,Mandetta se corrompeu a corrupção. VazaaaMandetta,Fri Apr 17 17:01:13 +0000 2020,0,0,False,NaN,NaN,False,NaN,NaN,NaN,False,NaN,NaN,NaN,NaN,0
66233,1251185636545085441,1022539297658953728,"O maior infectologista do mundo,Didier Raoult,...",Fri Apr 17 16:27:56 +0000 2020,5,18,True,7.159120e+17,Fri Apr 17 17:01:16 +0000 2020,False,NaN,NaN,NaN,False,NaN,NaN,NaN,NaN,0
66235,1250893581453332483,58951368,Morre um ministro. Nasce um candidato?,Thu Apr 16 21:07:24 +0000 2020,803,14164,False,NaN,NaN,False,NaN,NaN,NaN,False,NaN,NaN,NaN,NaN,0

In [20]:
#gerando pares de tweets generico - Por amostra
sample_size = 10000
pair_generics = [] #lista de dicionario correspondente aos pares
list_tweet_generics = generics["text"].tolist() #transformando tweets em lista

for i in range(sample_size):
  pair_gen = random.sample(list_tweet_generics, 2)
  pair_generics.append({"tweet_1": pair_gen[0], "tweet_2": pair_gen[1], "Class": 0, "Conflict": np.nan})

pair_generics_df = pd.DataFrame(pair_generics) #transformando a lista de dicionarios em df
pair_generics_df

,tweet_1,tweet_2,Class,Conflict
0,"Demorou, vá com Deus URGENTE: Bolsonaro exon...",parece que as viúvas do mandetta esqueceram qu...,0,NaN
1,E eu que li a notícia com “Mandetta demite Bol...,mandetta é um oasis de lucidez no meio de um m...,0,NaN
2,O Mandetta vai tomar naaaaa...... Jacaaaaaaaa !,"Bolsonaro demitindo Mandetta, Babu perdendo o ...",0,NaN
3,Quem em sã consciência demite um ministro da s...,Minha mae vai rasga a boca falando mal do bono...,0,NaN
4,So queria mostrar a minha proposta de emenda a...,Nelson Erich é o novo Ministro sa Saúde! #Bols...,0,NaN
...,...,...,...,...
9995,VOCE NÃO GOSTOU QUE MANDETTA SAIU FODASE EU AD...,Máquina bolsonarista começa a propagar ‘dossiê...,0,NaN
9996,"Agora é 8 ou 80, eu não acho o fim do mundo o ...",Lula: Mandetta era um privatista do sistema de...,0,NaN
9997,mandetta vai se candidatar já nas próximas ele...,Enfim o Mandetta saiu,0,NaN
9998,"Olá Sr Presidente Jair Bolsonaro, boa noite. O...",mandetta foi demitido por fazer o mínimo no me...,0,NaN
9999,[16/4 20:03] Amanda: você postou no status do ...,A próxima entrevista do Roda Viva vai ser com ...,0,NaN

In [21]:
#exibindo uma pequena amostra

for i in range(10):
  #printando na ordem - Replied tweet - tweet_original
  print(f'Tweet_1: {pair_generics_df.iloc[i]["tweet_1"]}')
  print(f'Tweet_2: {pair_generics_df.iloc[i]["tweet_2"]}')
  print()

Tweet_1: Demorou, vá com Deus   URGENTE: Bolsonaro exonera Mandetta do Ministério da Saúde
Tweet_2: parece que as viúvas do mandetta esqueceram que ele fechou o departamento de HIV/AIDS

Tweet_1: E eu que li a notícia com “Mandetta demite Bolsonaro “ Seria meu sonho
Tweet_2: mandetta é um oasis de lucidez no meio de um mainstream politico totalmente polarizado

Tweet_1: O Mandetta vai tomar naaaaa......  Jacaaaaaaaa !
Tweet_2: Bolsonaro demitindo Mandetta, Babu perdendo o lider dnv, mais um dia q o brasileiro não sorri

Tweet_1: Quem em sã consciência demite um ministro da saúde em plena pandemia???  Só Bolsonaro mesmo,  #BolsonaroVirus coitado do Mandetta, demitido por fazer o certo
Tweet_2: Minha mae vai rasga a boca falando mal do bonozoro e desse novo ministros pq ela queria o mandetta

Tweet_1: So queria mostrar a minha proposta de emenda a constituição: proibido o acesso qualquer pessoa que não defenda o SUS de a qualquer atendimento médico.  O que acham?  ps.: vai se fuder mandetta e bolsonaro
Tweet_2: Nelson Erich é o novo Ministro sa Saúde! #BolsonatoTemRazao By Mandetta!

Tweet_1: Bolsonaro demite Mandetta e coloca o Brasil no piloto automático.  Rumo a um prédio
Tweet_2: "Você conversa hoje, a pessoa entende, diz que concorda, depois muda de ideia e fala tudo diferente. Você vai, conversa, parece que está tudo acertado e, em seguida, o camarada muda o discurso de novo. Já chega, né? Já ajudamos bastante."

Tweet_1: GloboNews sai da coletiva do Mandetta e corta para o presidente: ele começa a tossir
Tweet_2: BDM Online [16.04.20 15:40] ++Mandetta foi chamado ao Planalto (GNews)

Tweet_1: Daqui há alguns dias muitos se perguntarão.  Mandetta, quem era mesmo? Ah, o que era ministro da saúde né?   Cairá no esquecimento!  Aproveite os 15 minutos de fama entre a esquerda e nova esquerda. Vai acabar! #ForaMaia
Tweet_2: Bolsonaro colocou um cara que é igual ao Mandetta. Ele é somente um palhaço com ego ferido e que precisava "sair por cima" nesse bate boca. Ele nunca se preocupou com o povo, apenas com a sua imagem.

Tweet_1: Em despedida, Mandetta elogia SUS e manda recados a Bolsonaro
Tweet_2: "O que os estrangeiros estão falando sobre a demissão de Mandetta, por Bolsonaro, em meio à pandemia do novo #coronavírus"

Tweet_1: Estou pagando pau sim para esse discurso do Mandetta. "A ciência é a luz"  #GloboNews
Tweet_2: Demitido por Bolsonaro, Mandetta diz que batalha do coronavírus está no "começo"

In [22]:
#convertendo para csv
pair_generics_df.to_csv("Mandetta_pares_genericos.csv", index=False, encoding="utf-8")
files.download("Mandetta_pares_genericos.csv")

# **Pares Tweet-Reply**

In [23]:
#filtrando apenas replys cujos tweets respondidos foram encontrados no dataset
replys = df.loc[(df["is_reply"] == True) & (df["reply_text"].notna())]
replys

,tweet_id,user_id_original,text,created_at_original,retweet_count,like_count,is_retweet,retweeter_user_id,retweet_created_at,is_quote,quoted_tweet_id,quoted_user_id,quoted_text,is_reply,reply_to_tweet_id,reply_to_user_id,reply_to_screen_name,reply_text,class
4,1250828255806009345,1039608133587554311,"Demorou, não deveria ne ter sido nomeado mande...",Thu Apr 16 16:47:50 +0000 2020,0,0,False,NaN,NaN,False,NaN,NaN,NaN,True,1.250553e+18,1.523748e+09,conexaopolitica,"“O dia que ele [Mandetta] sair, eu saio junto ...",1
13,1250828263976558593,170400715,"Como uma cobra ratoeira, está o senhor senador...",Thu Apr 16 16:47:52 +0000 2020,0,0,False,NaN,NaN,False,NaN,NaN,NaN,True,1.250796e+18,7.374596e+07,alvarodias_,A maioria esmagadora dos brasileiros é contrár...,1
18,1250821578318897156,35219319,#ForaMandettaTraira Eu não fui entrevistada!...,Thu Apr 16 16:21:18 +0000 2020,12,23,True,3.127892e+09,Thu Apr 16 16:47:55 +0000 2020,False,NaN,NaN,NaN,True,1.250796e+18,7.374596e+07,alvarodias_,A maioria esmagadora dos brasileiros é contrár...,1
32,1250828326454923267,1095129896630841345,Mandetta é um TRAIDOR!!!! #ForaMandettaUrgente,Thu Apr 16 16:48:06 +0000 2020,0,0,False,NaN,NaN,False,NaN,NaN,NaN,True,1.250783e+18,3.352020e+07,Rconstantino,Mandetta e sua política de isolamento estão lo...,1
101,1250828470004957186,1244304665317179398,"Mandetta, ficou deslumbrado ao microfone e o t...",Thu Apr 16 16:48:41 +0000 2020,0,0,False,NaN,NaN,False,NaN,NaN,NaN,True,1.250738e+18,2.880933e+09,o_antagonista,Demissão de Mandetta é rejeitada por 76% dos b...,1
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
66195,1251183728342249474,1151133589746008065,"Parabéns ao ex ministro e toda equipe, num mom...",Fri Apr 17 16:20:21 +0000 2020,0,0,False,NaN,NaN,False,NaN,NaN,NaN,True,1.251148e+18,2.043690e+08,laurojardim,Mandetta deixa ministério cantando.,1
66196,1251183729441214464,30752253,"Cadê a máscara e distanciamento, Mandetta ? Ah...",Fri Apr 17 16:20:21 +0000 2020,0,0,False,NaN,NaN,False,NaN,NaN,NaN,True,1.251148e+18,2.043690e+08,laurojardim,Mandetta deixa ministério cantando.,1
66198,1251183734587633665,917045970931798016,Como sou uma senhora fina não vou escrever o q...,Fri Apr 17 16:20:22 +0000 2020,0,0,False,NaN,NaN,False,NaN,NaN,NaN,True,1.250907e+18,4.009595e+07,SenadoFederal,Senadores se manifestam sobre demissão de Mand...,1
66221,1251193985634353154,1230272598480760834,"O ex Ministro da Saúde, Luiz Henrique Mandett...",Fri Apr 17 17:01:06 +0000 2020,0,0,False,NaN,NaN,False,NaN,NaN,NaN,True,1.251175e+18,1.061750e+08,JovemPanNews,"O ex-ministro da saúde, Luiz Henrique Mandetta...",1
66223,1251193989069488129,918828327489679362,2- Mas não queria correr o risco de contaminar...,Fri Apr 17 17:01:07 +0000 2020,0,0,False,NaN,NaN,False,NaN,NaN,NaN,True,1.251194e+18,9.188283e+17,0_RobinSchmidt,"1-Pessoal estou com duvida, no começo o Mandet...",1

In [24]:
replys[replys['reply_text'].str.contains('eu vendo a #AbortoNAO subir e lembrando dessas', na=False)]

Empty DataFrame
Columns: [tweet_id, user_id_original, text, created_at_original, retweet_count, like_count, is_retweet, retweeter_user_id, retweet_created_at, is_quote, quoted_tweet_id, quoted_user_id, quoted_text, is_reply, reply_to_tweet_id, reply_to_user_id, reply_to_screen_name, reply_text, class]
Index: []

In [25]:
#Gerando pares (por reply)
pair_replys = [] #lista de dicionario que irá armazenar os pares
list_tweet_replys = replys["text"].tolist() #transformando tweets do df em lista de tweets
list_replys = replys["reply_text"].tolist() #transformando replys do df em lista de replys

for i in range(len(list_tweet_replys)):
  pair_replys.append({"tweet_1":  list_replys[i], "tweet_2": list_tweet_replys[i], "Class": 1, "Conflict": np.nan})

pair_replys_df = pd.DataFrame(pair_replys)
pair_replys_df

,tweet_1,tweet_2,Class,Conflict
0,"“O dia que ele [Mandetta] sair, eu saio junto ...","Demorou, não deveria ne ter sido nomeado mande...",1,NaN
1,A maioria esmagadora dos brasileiros é contrár...,"Como uma cobra ratoeira, está o senhor senador...",1,NaN
2,A maioria esmagadora dos brasileiros é contrár...,#ForaMandettaTraira Eu não fui entrevistada!...,1,NaN
3,Mandetta e sua política de isolamento estão lo...,Mandetta é um TRAIDOR!!!! #ForaMandettaUrgente,1,NaN
4,Demissão de Mandetta é rejeitada por 76% dos b...,"Mandetta, ficou deslumbrado ao microfone e o t...",1,NaN
...,...,...,...,...
6474,Mandetta deixa ministério cantando.,"Parabéns ao ex ministro e toda equipe, num mom...",1,NaN
6475,Mandetta deixa ministério cantando.,"Cadê a máscara e distanciamento, Mandetta ? Ah...",1,NaN
6476,Senadores se manifestam sobre demissão de Mand...,Como sou uma senhora fina não vou escrever o q...,1,NaN
6477,"O ex-ministro da saúde, Luiz Henrique Mandetta...","O ex Ministro da Saúde, Luiz Henrique Mandett...",1,NaN
6478,"1-Pessoal estou com duvida, no começo o Mandet...",2- Mas não queria correr o risco de contaminar...,1,NaN

In [26]:
for i in range(10):
  #printando na ordem - Replied tweet - tweet_original
  print(f'Tweet_1: {pair_replys_df.iloc[i]["tweet_1"]}')
  print(f'Tweet_2: {pair_replys_df.iloc[i]["tweet_2"]}')
  print()

Tweet_1: “O dia que ele [Mandetta] sair, eu saio junto com ele”, afirma João Gabbardo
Tweet_2: Demorou, não deveria ne ter sido nomeado mandetta traidor

Tweet_1: A maioria esmagadora dos brasileiros é contrária à demissão de Mandetta: 76,2% dos entrevistados discordam do afastamento do ministro da Saúde, segundo pesquisa realizada pelo Atlas Político. Vc concorda com o resultado da pesquisa?   via
Tweet_2: Como uma cobra ratoeira, está o senhor senador, pronto para dar o bote.  Então Mandetta tem que continuar??? O senhor não engana ninguém!

Tweet_1: A maioria esmagadora dos brasileiros é contrária à demissão de Mandetta: 76,2% dos entrevistados discordam do afastamento do ministro da Saúde, segundo pesquisa realizada pelo Atlas Político. Vc concorda com o resultado da pesquisa?   via
Tweet_2: #ForaMandettaTraira   Eu não fui entrevistada!  Mas posso incluir uma enquete neste post:  Demissão do Mandetta, qual a sua opinião?

Tweet_1: Mandetta e sua política de isolamento estão longe de representar a visão única existente na comunidade médica. Recebi de um respeitado médico uma mensagem de desabafo justamente pq ele e vários pares estão revoltados com essa idolatria toda ao ministro.
Tweet_2: Mandetta é um TRAIDOR!!!! #ForaMandettaUrgente

Tweet_1: Demissão de Mandetta é rejeitada por 76% dos brasileiros
Tweet_2: Mandetta, ficou deslumbrado ao microfone e o tempo passou e os problemas aumentaram....

Tweet_1: O ministro da Saúde, Henrique Mandetta, disse há pouco que a troca de comando na pasta deverá acontecer entre hoje e amanhã.
Tweet_2: Que o Mandetta va tarde

Tweet_1: Quem era Mandetta antes de virar Ministro da Saúde? O que fez no ministério no período anterior à epidemia?
Tweet_2: Não sei porque estão criticando o  por demitir o . O Ministro vem pedindo para que todos fiquem em casa.... Então, o presidente está fazendo a vontade do Mandetta.  FIQUE EM CASA meu Ex-ministro!

Tweet_1: A maioria esmagadora dos brasileiros é contrária à demissão de Mandetta: 76,2% dos entrevistados discordam do afastamento do ministro da Saúde, segundo pesquisa realizada pelo Atlas Político. Vc concorda com o resultado da pesquisa?   via
Tweet_2: Bora lá provar para o senhor senador Alvaro Dias   Pergunta: Você quer que o Bolsonaro demita o Mandetta?

Tweet_1: Parece que é verdade, veja a reportagem de 2018 sobre o caso, só isso já é suficiente para a demissão dele do cargo de ministro, coisa feia  o Brasil não merece tanta traição, você sempre recebeu gordos salários pagos por nós.
Tweet_2: Eu escutei o dia q Mandetta "desceu a lenha na Prevent Sénior, achei muito esquisito aquela forte e segura de si. Esse cara só tem retórica é um sórdido. Ontem 15/04/20 as medidas tomadas pelo MS são as mesmas de 30 dias atrás. Tudo no gerúndio: estamos fazendo, provideciando.

Tweet_1: Planalto investiga assessores de Mandetta e prepara dossiê, diz revista
Tweet_2: Do nada o Mandetta morrendo  de  "ataque cardiaco"

In [27]:
#convertendo para csv
pair_replys_df.to_csv("Mandetta_pares_reply.csv", index=False, encoding="utf-8")
files.download("Mandetta_pares_reply.csv")

# **Pares Quote-Tweet**

In [28]:
#filtrando apenas quotes cujos tweets respondidos foram encontrados no dataset
quoteds = df.loc[(df["is_quote"] == True) & (df["quoted_text"].notna())]
quoteds

,tweet_id,user_id_original,text,created_at_original,retweet_count,like_count,is_retweet,retweeter_user_id,retweet_created_at,is_quote,quoted_tweet_id,quoted_user_id,quoted_text,is_reply,reply_to_tweet_id,reply_to_user_id,reply_to_screen_name,reply_text,class
9,1250828262059761664,160722408,Muita Tristeza !!! Muita !!!,Thu Apr 16 16:47:51 +0000 2020,0,0,False,NaN,NaN,True,1.250818e+18,1.109234e+18,"Segundo o leitor(sic), Mandetta informou aos a...",False,NaN,NaN,NaN,NaN,2
17,1250828274525245441,1508531576,Nata azeda. #ForaMandettaUrgente,Thu Apr 16 16:47:54 +0000 2020,0,0,False,NaN,NaN,True,1.250654e+18,6.125107e+07,"A Pepa quer a permanência de Mandetta. Pepa, M...",False,NaN,NaN,NaN,NaN,2
21,1250828291512156161,3313618782,"""O ministro da Saúde, Luiz Henrique Mandetta d...",Thu Apr 16 16:47:58 +0000 2020,0,0,False,NaN,NaN,True,1.250827e+18,2.076660e+07,"O ministro da Saúde, Luiz Henrique Mandetta di...",False,NaN,NaN,NaN,NaN,2
22,1250828291688345600,1081020435037335558,Roque ou Liminha,Thu Apr 16 16:47:58 +0000 2020,0,0,False,NaN,NaN,True,1.250817e+18,2.840796e+07,Sílvio Santos também indica nome a Bolsonaro p...,False,NaN,NaN,NaN,NaN,2
26,1250828305848205313,3433331123,Ele vai trabalhar em novela da Globo.,Thu Apr 16 16:48:02 +0000 2020,0,0,False,NaN,NaN,True,1.250738e+18,2.880933e+09,Demissão de Mandetta é rejeitada por 76% dos b...,False,NaN,NaN,NaN,NaN,2
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
66216,1251193977522532352,551460208,Ótima thread sobre a questão Bolsonaro x Mande...,Fri Apr 17 17:01:04 +0000 2020,0,0,False,NaN,NaN,True,1.251141e+18,1.412440e+07,Vamos olhar esta história pelo ponto de vista ...,False,NaN,NaN,NaN,NaN,2
66217,1251193977631580160,132240954,"O poço, ele não tem fim",Fri Apr 17 17:01:04 +0000 2020,0,0,False,NaN,NaN,True,1.251162e+18,1.004512e+18,Bolsonaro acabou de demitir o Presidente do CN...,False,NaN,NaN,NaN,NaN,2
66224,1251193990403293187,160948465,E o que o Mandetta fez para isso não acontecer...,Fri Apr 17 17:01:08 +0000 2020,0,0,False,NaN,NaN,True,1.251125e+18,1.966702e+07,"Da Síria à guerra na pandemia, uma repórter é ...",False,NaN,NaN,NaN,NaN,2
66226,1251193994853351426,566767440,"Tambem gostaria de me livrar deles, mais Witze...",Fri Apr 17 17:01:09 +0000 2020,0,0,False,NaN,NaN,True,1.251190e+18,1.828614e+07,Pronto! O presidente Jair Bolsonaro já está li...,False,NaN,NaN,NaN,NaN,2
66228,1251193997521047554,1223816739080888320,tá liberado abraço durante a quarentena,Fri Apr 17 17:01:09 +0000 2020,0,0,False,NaN,NaN,True,1.251148e+18,2.043690e+08,Mandetta deixa ministério cantando.,False,NaN,NaN,NaN,NaN,2

In [29]:
#Gerando pares (por quote)
pair_quote = [] #lista de dicionario que irá armazenar os pares
list_tweet_quote = quoteds["text"].tolist() #transformando tweets do df em lista de tweets
list_quote = quoteds["quoted_text"].tolist() #transformando quote do df em lista de quotes

for i in range(len(list_tweet_quote)):
  pair_quote.append({"tweet_1": list_quote[i], "tweet_2": list_tweet_quote[i] , "Class": 2, "Conflict": np.nan})

pair_quote_df = pd.DataFrame(pair_quote)
pair_quote_df

,tweet_1,tweet_2,Class,Conflict
0,"Segundo o leitor(sic), Mandetta informou aos a...",Muita Tristeza !!! Muita !!!,2,NaN
1,"A Pepa quer a permanência de Mandetta. Pepa, M...",Nata azeda. #ForaMandettaUrgente,2,NaN
2,"O ministro da Saúde, Luiz Henrique Mandetta di...","""O ministro da Saúde, Luiz Henrique Mandetta d...",2,NaN
3,Sílvio Santos também indica nome a Bolsonaro p...,Roque ou Liminha,2,NaN
4,Demissão de Mandetta é rejeitada por 76% dos b...,Ele vai trabalhar em novela da Globo.,2,NaN
...,...,...,...,...
20795,Vamos olhar esta história pelo ponto de vista ...,Ótima thread sobre a questão Bolsonaro x Mande...,2,NaN
20796,Bolsonaro acabou de demitir o Presidente do CN...,"O poço, ele não tem fim",2,NaN
20797,"Da Síria à guerra na pandemia, uma repórter é ...",E o que o Mandetta fez para isso não acontecer...,2,NaN
20798,Pronto! O presidente Jair Bolsonaro já está li...,"Tambem gostaria de me livrar deles, mais Witze...",2,NaN
20799,Mandetta deixa ministério cantando.,tá liberado abraço durante a quarentena,2,NaN

In [30]:
for i in range(10):
  #printando na ordem - Quoted tweet - tweet
  print(f'Tweet_1: {pair_quote_df.iloc[i]["tweet_1"]}')
  print(f'Tweet_2: {pair_quote_df.iloc[i]["tweet_2"]}')
  print()

Tweet_1: Segundo o leitor(sic), Mandetta informou aos aliados que sua saída é certa. Acontecerá hoje ou mais tardar amanhã.  Como se sentem com esse anúncio, amigos?
Tweet_2: Muita Tristeza !!! Muita !!!

Tweet_1: A Pepa quer a permanência de Mandetta. Pepa, Maia, Alcolumbre. Só a nata do Congresso.
Tweet_2: Nata azeda. #ForaMandettaUrgente

Tweet_1: O ministro da Saúde, Luiz Henrique Mandetta disse nesta quinta-feira, 16, que a covid-19 irá marcar uma divisão histórica no Século 21.  #MeiaHora
Tweet_2: "O ministro da Saúde, Luiz Henrique Mandetta disse nesta quinta-feira, 16, que a covid-19 irá marcar uma divisão histórica no Século 21. 'O século 21 começou. Antes da covid e após covid. Vai ser uma divisão histórica. Isso vai estar em qualquer livro', disse o ministro"

Tweet_1: Sílvio Santos também indica nome a Bolsonaro para lugar de Mandetta
Tweet_2: Roque ou Liminha

Tweet_1: Demissão de Mandetta é rejeitada por 76% dos brasileiros
Tweet_2: Ele vai trabalhar em novela da Globo.

Tweet_1: Lula: Mandetta era um privatista do sistema de saúde | Revista Fórum
Tweet_2: Lulão precisa aparecer mais pra esclarecer essa esquerda desesperada que já estava abraçando o Pau Mandetta...

Tweet_1: Mandetta e sua política de isolamento estão longe de representar a visão única existente na comunidade médica. Recebi de um respeitado médico uma mensagem de desabafo justamente pq ele e vários pares estão revoltados com essa idolatria toda ao ministro.
Tweet_2: Toda unanimidade é burra

Tweet_1: E agora  ?
Tweet_2: #STFVergonhaNacional  #AbortoNao  MANDETTA CANALHA INIMIGO DO BRASIL  NHONHO BOTAFOGO MAIA FDP SAFADO TENHO NOJO DO STF PETISTA, bando de BOSTAS NOJENTOS

Tweet_1: MANDETTA  - contratou empresa que doou para a sua campanha - comprou itens superfaturados - não tem estratégia a não ser prolongar o isolamento  E agora mais essa!  Ah, mas querem que você acredite que ele vai cair porque BOLSONARO está com "ciúmes".  Pode acreditar amiguinho
Tweet_2: Plasma é IMPORTANTE na testagem PRA CURAR ou CRIAR VACINA ou estou enganada?  NÃO SABIA dos problemas que desde 2017 JÁ ROLAVA no  ?

Tweet_1: Mandetta gastando 25 milhões com gel pra nego dar a bunda é foda Mais foda ainda o presidente não ver isso aí Vai deixar pra mandar o cara embora agora com a mídia mamando ele
Tweet_2: 1- São 25 milhões de UNIDADES de gel, no valor de R$ 4 milhões   2- O Mandetta n teve ação direta na renovação desse contrato (é o mesmo q distribui camisinha etc)  Mas como bolsonarista é desonesto, vai espalhar que cara foi lá e resolveu torrar R$ 25 milhões pra galera dar o cu

In [31]:
#convertendo para csv
pair_quote_df.to_csv("Mandetta_pares_quote.csv", index=False, encoding="utf-8")
files.download("Mandetta_pares_quote.csv")

In [32]:
#concatenando os datasets parciais:
df_mandetta = pd.concat([pair_generics_df, pair_replys_df, pair_quote_df], ignore_index=True, axis = 0)
df_mandetta

,tweet_1,tweet_2,Class,Conflict
0,"Demorou, vá com Deus URGENTE: Bolsonaro exon...",parece que as viúvas do mandetta esqueceram qu...,0,NaN
1,E eu que li a notícia com “Mandetta demite Bol...,mandetta é um oasis de lucidez no meio de um m...,0,NaN
2,O Mandetta vai tomar naaaaa...... Jacaaaaaaaa !,"Bolsonaro demitindo Mandetta, Babu perdendo o ...",0,NaN
3,Quem em sã consciência demite um ministro da s...,Minha mae vai rasga a boca falando mal do bono...,0,NaN
4,So queria mostrar a minha proposta de emenda a...,Nelson Erich é o novo Ministro sa Saúde! #Bols...,0,NaN
...,...,...,...,...
37274,Vamos olhar esta história pelo ponto de vista ...,Ótima thread sobre a questão Bolsonaro x Mande...,2,NaN
37275,Bolsonaro acabou de demitir o Presidente do CN...,"O poço, ele não tem fim",2,NaN
37276,"Da Síria à guerra na pandemia, uma repórter é ...",E o que o Mandetta fez para isso não acontecer...,2,NaN
37277,Pronto! O presidente Jair Bolsonaro já está li...,"Tambem gostaria de me livrar deles, mais Witze...",2,NaN
37278,Mandetta deixa ministério cantando.,tá liberado abraço durante a quarentena,2,NaN

In [33]:
#convertendo para csv
df_mandetta.to_csv("Mandetta_pares.csv", index=False, encoding="utf-8")
files.download("Mandetta_pares.csv")