# **Projeto de Graduação em Computação II [2026-Q1]**

Universidade Federal do ABC

Orientador Carlos da Silva dos Santos

### **EQUIPE**

---

Caio Cardoso Dos Santos - RA: 11202021632

Victor Ravazio de Lima - RA: 11201920941

### **IMPLEMENTAÇÃO**
---

In [ ]:
# modulo para importar dataset a partir de um link
!pip install gdown

Requirement already satisfied: gdown in /usr/local/lib/python3.12/dist-packages (5.2.2)
Requirement already satisfied: beautifulsoup4 in /usr/local/lib/python3.12/dist-packages (from gdown) (4.13.5)
Requirement already satisfied: filelock in /usr/local/lib/python3.12/dist-packages (from gdown) (3.29.0)
Requirement already satisfied: requests[socks] in /usr/local/lib/python3.12/dist-packages (from gdown) (2.32.4)
Requirement already satisfied: tqdm in /usr/local/lib/python3.12/dist-packages (from gdown) (4.67.3)
Requirement already satisfied: soupsieve>1.2 in /usr/local/lib/python3.12/dist-packages (from beautifulsoup4->gdown) (2.8.3)
Requirement already satisfied: typing-extensions>=4.0.0 in /usr/local/lib/python3.12/dist-packages (from beautifulsoup4->gdown) (4.15.0)
Requirement already satisfied: charset_normalizer<4,>=2 in /usr/local/lib/python3.12/dist-packages (from requests[socks]->gdown) (3.4.7)
Requirement already satisfied: idna<4,>=2.5 in /usr/local/lib/python3.12/dist-packages (from requests[socks]->gdown) (3.13)
Requirement already satisfied: urllib3<3,>=1.21.1 in /usr/local/lib/python3.12/dist-packages (from requests[socks]->gdown) (2.5.0)
Requirement already satisfied: certifi>=2017.4.17 in /usr/local/lib/python3.12/dist-packages (from requests[socks]->gdown) (2026.4.22)
Requirement already satisfied: PySocks!=1.5.7,>=1.5.6 in /usr/local/lib/python3.12/dist-packages (from requests[socks]->gdown) (1.7.1)

In [ ]:
#Bibliotecas
import pandas as pd
import numpy as np
from google.colab import files
import gdown
import matplotlib.pyplot as plt
import random

In [ ]:
# baixando dataset para o collab
import gdown

file_id = "1F-MsPMejwbxEixBvcZF2tK5YQYA_a6mN"
url = f"https://drive.google.com/uc?id={file_id}"

gdown.download(url, "contas_suspensas.csv", quiet=False)

Downloading...
From: https://drive.google.com/uc?id=1F-MsPMejwbxEixBvcZF2tK5YQYA_a6mN
To: /content/contas_suspensas.csv
100%|██████████| 17.2M/17.2M [00:00<00:00, 55.6MB/s]

'contas_suspensas.csv'

In [ ]:
#carregando o dataset
df = pd.read_csv ("contas_suspensas.csv")
df.head()

,tweet_id,user_id_original,text,created_at_original,retweet_count,like_count,is_retweet,retweeter_user_id,retweet_created_at,is_quote,quoted_tweet_id,quoted_user_id,quoted_text,is_reply,reply_to_tweet_id,reply_to_user_id,reply_to_screen_name,reply_text,class
0,1286723608866324480,174818242,O bom dessa censura toda é que fica clara a in...,Fri Jul 24 18:03:09 +0000 2020,431,1788,True,1.244302e+18,Fri Jul 24 19:20:09 +0000 2020,False,NaN,NaN,NaN,False,NaN,NaN,NaN,NaN,0
1,1286734747629170688,3092434408,Mude a localização para acessar meus tweets: 1...,Fri Jul 24 18:47:24 +0000 2020,631,1693,True,9.715975e+17,Fri Jul 24 19:20:09 +0000 2020,False,NaN,NaN,NaN,False,NaN,NaN,NaN,NaN,0
2,1286713348063666186,1090291692744466433,#URGENTE: Após pedido de Alexandre de Moraes (...,Fri Jul 24 17:22:22 +0000 2020,810,1801,True,3.339003e+09,Fri Jul 24 19:20:09 +0000 2020,False,NaN,NaN,NaN,False,NaN,NaN,NaN,NaN,0
3,1286719270555201537,1196864541726060544,24.07.2020 Dia Nacional da Censura do Twitter...,Fri Jul 24 17:45:54 +0000 2020,5,7,True,8.623623e+17,Fri Jul 24 19:20:09 +0000 2020,False,NaN,NaN,NaN,False,NaN,NaN,NaN,NaN,0
4,1286740416457572353,2822662924,"Caçaram a conta do Roberto Jefferson, e agora ...",Fri Jul 24 19:09:56 +0000 2020,6,19,True,1.284922e+18,Fri Jul 24 19:20:09 +0000 2020,False,NaN,NaN,NaN,False,NaN,NaN,NaN,NaN,0

In [ ]:
#numero total de instancias no dataset
df.shape

(51521, 19)

In [ ]:
df

,tweet_id,user_id_original,text,created_at_original,retweet_count,like_count,is_retweet,retweeter_user_id,retweet_created_at,is_quote,quoted_tweet_id,quoted_user_id,quoted_text,is_reply,reply_to_tweet_id,reply_to_user_id,reply_to_screen_name,reply_text,class
0,1286723608866324480,174818242,O bom dessa censura toda é que fica clara a in...,Fri Jul 24 18:03:09 +0000 2020,431,1788,True,1.244302e+18,Fri Jul 24 19:20:09 +0000 2020,False,NaN,NaN,NaN,False,NaN,NaN,NaN,NaN,0
1,1286734747629170688,3092434408,Mude a localização para acessar meus tweets: 1...,Fri Jul 24 18:47:24 +0000 2020,631,1693,True,9.715975e+17,Fri Jul 24 19:20:09 +0000 2020,False,NaN,NaN,NaN,False,NaN,NaN,NaN,NaN,0
2,1286713348063666186,1090291692744466433,#URGENTE: Após pedido de Alexandre de Moraes (...,Fri Jul 24 17:22:22 +0000 2020,810,1801,True,3.339003e+09,Fri Jul 24 19:20:09 +0000 2020,False,NaN,NaN,NaN,False,NaN,NaN,NaN,NaN,0
3,1286719270555201537,1196864541726060544,24.07.2020 Dia Nacional da Censura do Twitter...,Fri Jul 24 17:45:54 +0000 2020,5,7,True,8.623623e+17,Fri Jul 24 19:20:09 +0000 2020,False,NaN,NaN,NaN,False,NaN,NaN,NaN,NaN,0
4,1286740416457572353,2822662924,"Caçaram a conta do Roberto Jefferson, e agora ...",Fri Jul 24 19:09:56 +0000 2020,6,19,True,1.284922e+18,Fri Jul 24 19:20:09 +0000 2020,False,NaN,NaN,NaN,False,NaN,NaN,NaN,NaN,0
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
51516,1287126460243873793,218276449,A escalada de Hang escancara a triste realidad...,Sat Jul 25 20:43:56 +0000 2020,0,0,False,NaN,NaN,True,1.287030e+18,195474607.0,Exclusivo: Luciano Hang obteve 55 empréstimos ...,False,NaN,NaN,NaN,NaN,2
51517,1287126481282510848,1265039279169863681,A CENSURA DO MINISTRO ALEXANDRE DE MORAES CONT...,Sat Jul 25 20:44:01 +0000 2020,0,0,False,NaN,NaN,False,NaN,NaN,NaN,False,NaN,NaN,NaN,NaN,0
51518,1287126483916468232,177756468,O que Alexandre de Moraes fez passa ao largo d...,Sat Jul 25 20:44:02 +0000 2020,0,0,False,NaN,NaN,False,NaN,NaN,NaN,False,NaN,NaN,NaN,NaN,0
51519,1286718273577517061,25858078,Vocês também estão sentindo que o clima aqui n...,Fri Jul 24 17:41:57 +0000 2020,899,17572,False,NaN,NaN,False,NaN,NaN,NaN,False,NaN,NaN,NaN,NaN,0
51520,1286763749404286978,1279134760716177408,O que vcs acham do STF ?,Fri Jul 24 20:42:39 +0000 2020,1731,12785,False,NaN,NaN,False,NaN,NaN,NaN,False,NaN,NaN,NaN,NaN,0

In [ ]:
df[df['reply_text'].str.contains('eu vendo a #AbortoNAO subir e lembrando dessas', na=False)]

Empty DataFrame
Columns: [tweet_id, user_id_original, text, created_at_original, retweet_count, like_count, is_retweet, retweeter_user_id, retweet_created_at, is_quote, quoted_tweet_id, quoted_user_id, quoted_text, is_reply, reply_to_tweet_id, reply_to_user_id, reply_to_screen_name, reply_text, class]
Index: []

In [ ]:
#classe 0
sum_class_0 = int ((df['class'] == 0).sum())
sum_class_0

14429

In [ ]:
#Classe 1
sum_class_1 = int ((df['class'] == 1).sum())
sum_class_1

20856

In [ ]:
#classe 2
sum_class_2 = int ((df['class'] == 2).sum())
sum_class_2

16236

In [ ]:
#numero de tweets genericos (não é quote nem reply)
generics = df.loc[(df["is_quote"] == False) & (df["is_reply"] == False)]
generics.shape[0]

14429

In [ ]:
#numero de tweets replys totais (com e sem respostas os respectivos tweets originais obtidos)
replys_tot = df.loc[df["is_reply"] == True]
replys_tot.shape[0]

21114

In [ ]:
#numero de tweets replys com respostas encontradas
replys = df.loc[(df["is_reply"]) & (df["reply_text"].notna())]
replys.shape[0]

5704

In [ ]:
#numero de quotes
quoteds_tot = df.loc[df["is_quote"] == True]
quoteds_tot.shape[0]

16236

In [ ]:
#numero de quotes usaveis
quoteds = df.loc[(df["is_quote"] == True) & (df["quoted_text"].notna())]
quoteds.shape[0]

16161

In [ ]:
#intersecções entre quotes e replys
replys_quotes = df.loc[(df["is_reply"] == True) & (df["is_quote"] == True)]
replys_quotes.shape[0]

258

In [ ]:
tot = generics.shape[0] + replys_tot.shape[0] + quoteds_tot.shape[0] - replys_quotes.shape[0]
tot

51521

In [ ]:
replys_tot.head()

,tweet_id,user_id_original,text,created_at_original,retweet_count,like_count,is_retweet,retweeter_user_id,retweet_created_at,is_quote,quoted_tweet_id,quoted_user_id,quoted_text,is_reply,reply_to_tweet_id,reply_to_user_id,reply_to_screen_name,reply_text,class
5,1286393059735937025,1184178787786936320,"Obrigado, Fiúza! Não tem que se desculpar. Pod...",Thu Jul 23 20:09:40 +0000 2020,617,8826,True,2.387179e+09,Fri Jul 24 19:20:09 +0000 2020,False,NaN,NaN,NaN,True,1.286356e+18,2.804950e+09,GFiuza_Oficial,NaN,1
7,1286742990355038208,1153697538949681152,Que estejamos livres da laia comunista q nos a...,Fri Jul 24 19:20:10 +0000 2020,0,0,False,NaN,NaN,False,NaN,NaN,NaN,True,1.286675e+18,1.252412e+18,AslamLeon_ofGOD,NaN,1
17,1286742996982149120,1266828023833276417,Comunista defendendo a censura. Nada de novo p...,Fri Jul 24 19:20:11 +0000 2020,0,0,False,NaN,NaN,False,NaN,NaN,NaN,True,1.286718e+18,2.585808e+07,ManuelaDavila,Vocês também estão sentindo que o clima aqui n...,1
20,1286742998798270466,964885771101589505,Respondam pra gente: Vocês são a favor de cens...,Fri Jul 24 19:20:12 +0000 2020,0,0,False,NaN,NaN,False,NaN,NaN,NaN,True,1.286724e+18,1.567197e+08,OGloboPolitica,NaN,1
32,1286743008453505025,140062328,"Não é bem assim , a censura da Crusoé não foi ...",Fri Jul 24 19:20:14 +0000 2020,0,0,False,NaN,NaN,False,NaN,NaN,NaN,True,1.286738e+18,1.624534e+08,aguedescartoon,NaN,1

# **Pares Tweets genéricos**

In [ ]:
generics = df.loc[(df["is_quote"] == False) & (df["is_reply"] == False)]
generics

,tweet_id,user_id_original,text,created_at_original,retweet_count,like_count,is_retweet,retweeter_user_id,retweet_created_at,is_quote,quoted_tweet_id,quoted_user_id,quoted_text,is_reply,reply_to_tweet_id,reply_to_user_id,reply_to_screen_name,reply_text,class
0,1286723608866324480,174818242,O bom dessa censura toda é que fica clara a in...,Fri Jul 24 18:03:09 +0000 2020,431,1788,True,1.244302e+18,Fri Jul 24 19:20:09 +0000 2020,False,NaN,NaN,NaN,False,NaN,NaN,NaN,NaN,0
1,1286734747629170688,3092434408,Mude a localização para acessar meus tweets: 1...,Fri Jul 24 18:47:24 +0000 2020,631,1693,True,9.715975e+17,Fri Jul 24 19:20:09 +0000 2020,False,NaN,NaN,NaN,False,NaN,NaN,NaN,NaN,0
2,1286713348063666186,1090291692744466433,#URGENTE: Após pedido de Alexandre de Moraes (...,Fri Jul 24 17:22:22 +0000 2020,810,1801,True,3.339003e+09,Fri Jul 24 19:20:09 +0000 2020,False,NaN,NaN,NaN,False,NaN,NaN,NaN,NaN,0
3,1286719270555201537,1196864541726060544,24.07.2020 Dia Nacional da Censura do Twitter...,Fri Jul 24 17:45:54 +0000 2020,5,7,True,8.623623e+17,Fri Jul 24 19:20:09 +0000 2020,False,NaN,NaN,NaN,False,NaN,NaN,NaN,NaN,0
4,1286740416457572353,2822662924,"Caçaram a conta do Roberto Jefferson, e agora ...",Fri Jul 24 19:09:56 +0000 2020,6,19,True,1.284922e+18,Fri Jul 24 19:20:09 +0000 2020,False,NaN,NaN,NaN,False,NaN,NaN,NaN,NaN,0
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
51515,1287126455516909570,1609283827,Um dia o capitão deles menospreza a entidade f...,Sat Jul 25 20:43:55 +0000 2020,0,0,False,NaN,NaN,False,NaN,NaN,NaN,False,NaN,NaN,NaN,NaN,0
51517,1287126481282510848,1265039279169863681,A CENSURA DO MINISTRO ALEXANDRE DE MORAES CONT...,Sat Jul 25 20:44:01 +0000 2020,0,0,False,NaN,NaN,False,NaN,NaN,NaN,False,NaN,NaN,NaN,NaN,0
51518,1287126483916468232,177756468,O que Alexandre de Moraes fez passa ao largo d...,Sat Jul 25 20:44:02 +0000 2020,0,0,False,NaN,NaN,False,NaN,NaN,NaN,False,NaN,NaN,NaN,NaN,0
51519,1286718273577517061,25858078,Vocês também estão sentindo que o clima aqui n...,Fri Jul 24 17:41:57 +0000 2020,899,17572,False,NaN,NaN,False,NaN,NaN,NaN,False,NaN,NaN,NaN,NaN,0
51520,1286763749404286978,1279134760716177408,O que vcs acham do STF ?,Fri Jul 24 20:42:39 +0000 2020,1731,12785,False,NaN,NaN,False,NaN,NaN,NaN,False,NaN,NaN,NaN,NaN,0

In [ ]:
#gerando pares de tweets generico - Por amostra
sample_size = 10000
pair_generics = [] #lista de dicionario correspondente aos pares
list_tweet_generics = generics["text"].tolist() #transformando tweets em lista

for i in range(sample_size):
  pair_gen = random.sample(list_tweet_generics, 2)
  pair_generics.append({"tweet_1": pair_gen[0], "tweet_2": pair_gen[1], "Class": 0, "Conflict": np.nan})

pair_generics_df = pd.DataFrame(pair_generics) #transformando a lista de dicionarios em df
pair_generics_df

,tweet_1,tweet_2,Class,Conflict
0,Guilherme Fiuza diz que Alexandre de Moraes nã...,Boletim das 17h01 do dia 24/07/2020 Situação ...,0,NaN
1,peço perdao pessoal nao e do meu feitio defend...,TWITTER DERRUBA CONTAS DOS DISSEMINADORES DE F...,0,NaN
2,Vejam agora no programa PINGO NOS IS o Roberto...,"Mano, grande mídia é muito fraquinha, mesmo Os...",0,NaN
3,Roberto Jefferson acaba de afirmar no Terça Li...,grande dia difícil,0,NaN
4,qual a sua Opniao sobre a Censura nas redes s...,ROBERTO JEFFERSON DENUNCIA PERFIL FALSO EM SEU...,0,NaN
...,...,...,...,...
9995,O estragadão falido e seus jornalistazinhos am...,((VERDADEIRA CENSURA)) DIZ ADVOGADO DE FAKHOUR...,0,NaN
9996,"E quanto a censura no Brasil, o Senhor vai con...",o que mais tem atrapalhado minha saúde mental ...,0,NaN
9997,Retido vai ficar o dos togados quando jogar ...,"E por, atos como esse,que o STF, não tem nenhu...",0,NaN
9998,"Vão ler esse furo da minha amiga pessoal, , qu...",hj eu recebi dois “achei q vc era mais alta” ...,0,NaN
9999,"passei mal de tanto comer comida japa hoje, gr...","Fábio Wajngarten classificou como ""censura"" e ...",0,NaN

In [ ]:
#exibindo uma pequena amostra

for i in range(10):
  #printando na ordem - Replied tweet - tweet_original
  print(f'Tweet_1: {pair_generics_df.iloc[i]["tweet_1"]}')
  print(f'Tweet_2: {pair_generics_df.iloc[i]["tweet_2"]}')
  print()

Tweet_1: Guilherme Fiuza diz que Alexandre de Moraes não passa de um tiranete e ultrapassou todos os limites
Tweet_2: Boletim das 17h01 do dia 24/07/2020  Situação atual: Sem chuvas na região do Grande ABC. (Fonte: Pluviômetros CEMADEN).  Cenário para as próximas horas: Céu parcialmente nublado a claro, sem chuva.  (+)

Tweet_1: peço perdao pessoal nao e do meu feitio defender a censura das pessoa apenas a de sara winter e allan terça livre
Tweet_2: TWITTER DERRUBA CONTAS DOS DISSEMINADORES DE FAKE NEWS:  ALLAN DOS SANTOS, SARA WINTER E BERNARDO!!!! UHUUUU!!!! QUEREM APOSTAR  QUE A TAG EM FAVOR DE SERGIO MORO VAI SUBIR AOS TRENDS ???

Tweet_1: Vejam agora no programa PINGO NOS IS o Roberto Jefferson aniquilando o STF
Tweet_2: Mano, grande mídia é muito fraquinha, mesmo Os Pingos nos Ís  As vezes eu vejo só pra ter uma noção do tipo de informação que tá chegando no povo

Tweet_1: Roberto Jefferson acaba de afirmar no Terça Livre que o escritório do Luís Roberto Barroso recebeu mais de 3 milhões de reais nesse mês.   #FreedomOfSpeech
Tweet_2: grande dia difícil

Tweet_1: qual a sua Opniao sobre a Censura  nas redes sociais ?, você sempre tão combativa e defensora dos direitos dos cidades a se manifestarem , não tenho visto sua Opniao a respeito ......
Tweet_2: ROBERTO JEFFERSON DENUNCIA PERFIL FALSO EM SEU NOME E DEMONSTRA QUE STF USOU EXPEDIENTE INADEQUADO

Tweet_1: #STFVergonhaNacional bando de lixo
Tweet_2: Essa música vem acalhar nesse momento de censura descarada.   Descubra "SING" de My Chemical Romance na Deezer

Tweet_1: Quem comemora a censura hoje, chora amanhã por não pode se expressar. Espero que o ódio não tome conta de nós brasileiros, os charlatões da toga estão abusando já. Estamos precisando do "cabo e do soldado", somente carreata não intimida bandidos.
Tweet_2: "No último ano e meio, a militância bolsonarista encheu o saco do Brasil defendendo intervenção militar e implantação do AI-5. Pois bem, nessa sexta-feira (24), acusam o Min. Alexandre de Moraes, de reeditar o AI-5." Militância Fake, #GovernoDeFraudes

Tweet_1: Qual será o teor do "textão" que os Generais de pantufa farão - se é que farão, pra "protestarem veementemente" contra mais um abuso cometido no âmbito do #InqueritoIlegal do #STF que #Censura e persegue quem os critica?  #STFVergonhaNacional #stfvergonhanacinal #CensuraNao
Tweet_2: #VozParaBernardoKuster Querem censurar a verdade para que a mentira prevaleça!

Tweet_1: Censura não ajuda, não resolve problemas e não é positiva para a democracia do Brasil, nem para os brasileiros... isso precisa mudar PR  !  Após mandado de Moraes, Twitter derruba perfis de conservadores
Tweet_2: Bom dia Rio Grande do AZUL !!! Um baita dia para todos aqui desta minha TIMEBLUE !!!

Tweet_1: Este miúdo é uma comédia tão grande
Tweet_2: Sabrinna está viciada em falar grande dia e isso me fez pensar no Bolsonaro pfv pare

In [ ]:
#convertendo para csv
pair_generics_df.to_csv("contas_suspensas_pares_genericos.csv", index=False, encoding="utf-8")
files.download("contas_suspensas_pares_genericos.csv")

# **Pares Tweet-Reply**

In [ ]:
#filtrando apenas replys cujos tweets respondidos foram encontrados no dataset
replys = df.loc[(df["is_reply"] == True) & (df["reply_text"].notna())]
replys

,tweet_id,user_id_original,text,created_at_original,retweet_count,like_count,is_retweet,retweeter_user_id,retweet_created_at,is_quote,quoted_tweet_id,quoted_user_id,quoted_text,is_reply,reply_to_tweet_id,reply_to_user_id,reply_to_screen_name,reply_text,class
17,1286742996982149120,1266828023833276417,Comunista defendendo a censura. Nada de novo p...,Fri Jul 24 19:20:11 +0000 2020,0,0,False,NaN,NaN,False,NaN,NaN,NaN,True,1.286718e+18,2.585808e+07,ManuelaDavila,Vocês também estão sentindo que o clima aqui n...,1
61,1286741006977818625,971792681293795328,Eu não consigo ler isso sem passar raiva desse...,Fri Jul 24 19:12:17 +0000 2020,2,5,True,7.541566e+17,Fri Jul 24 19:20:21 +0000 2020,True,1.286724e+18,357030742.0,Alexandre determina e Twitter bloqueia perfis ...,True,1.286735e+18,2.804950e+09,GFiuza_Oficial,O tiranete Alexandre de Moraes passou de todos...,2
67,1286743042100256769,587385641,"Isso é total ditadura!! Mas e o executivo , nã...",Fri Jul 24 19:20:22 +0000 2020,0,0,False,NaN,NaN,False,NaN,NaN,NaN,True,1.286735e+18,2.804950e+09,GFiuza_Oficial,O tiranete Alexandre de Moraes passou de todos...,1
74,1286723919211364358,1116451149660467207,"... o PGR, Augusto Aras, já opinou pela conces...",Fri Jul 24 18:04:23 +0000 2020,136,658,True,1.027624e+18,Fri Jul 24 19:20:23 +0000 2020,False,NaN,NaN,NaN,True,1.286724e+18,1.116451e+18,ManssurJoao,"Hoje, 24/07, Fakhoury e demais investigados pe...",1
76,1286743048148389888,283272318,"Dessa vez a culpa não foi do Twitter, e sim do...",Fri Jul 24 19:20:23 +0000 2020,0,0,False,NaN,NaN,False,NaN,NaN,NaN,True,1.286711e+18,1.055710e+18,jc38_oliver,É verdade que o Twitter derrubou várias contas...,1
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
51405,1287124827824889858,1069873580442353664,"Estamos de saco cheio de falar, escrever e não...",Sat Jul 25 20:37:27 +0000 2020,0,0,False,NaN,NaN,False,NaN,NaN,NaN,True,1.287121e+18,4.720338e+08,crisbrasilreal,#BOBJEFF Temos que lutar para que a luz da de...,1
51411,1287124931055161345,1250161817072132098,Acabei de receber um aviso do twitter relatand...,Sat Jul 25 20:37:51 +0000 2020,0,0,False,NaN,NaN,False,NaN,NaN,NaN,True,1.286775e+18,1.184179e+18,luislacombereal,Não há como aceitar a censura. Não há como ace...,1
51413,1287124957395394561,40484588,"Censura relativa, ele fez questão de dizer e f...",Sat Jul 25 20:37:58 +0000 2020,0,0,False,NaN,NaN,False,NaN,NaN,NaN,True,1.287121e+18,9.961883e+07,RodrigoGiacomet,LAMENTÁVEL ! Postura ditatorial e autoritária ...,1
51425,1287125204234203136,250659299,"Esse Lulu boquinha de veludo é uma piada, a f...",Sat Jul 25 20:38:56 +0000 2020,0,0,False,NaN,NaN,False,NaN,NaN,NaN,True,1.287074e+18,1.187347e+18,PATRIOTASBR38,Quanto você pensa que os ministros do STF não ...,1
51510,1287126362051039232,1129490121290649601,O pior da história!!! #STFVergonhaNacional Qu...,Sat Jul 25 20:43:33 +0000 2020,0,0,False,NaN,NaN,False,NaN,NaN,NaN,True,1.287083e+18,1.208590e+18,BolsoFenix,"- Agora, no Brasil, é crime criticar e questio...",1

In [ ]:
replys[replys['reply_text'].str.contains('eu vendo a #AbortoNAO subir e lembrando dessas', na=False)]

Empty DataFrame
Columns: [tweet_id, user_id_original, text, created_at_original, retweet_count, like_count, is_retweet, retweeter_user_id, retweet_created_at, is_quote, quoted_tweet_id, quoted_user_id, quoted_text, is_reply, reply_to_tweet_id, reply_to_user_id, reply_to_screen_name, reply_text, class]
Index: []

In [ ]:
#Gerando pares (por reply)
pair_replys = [] #lista de dicionario que irá armazenar os pares
list_tweet_replys = replys["text"].tolist() #transformando tweets do df em lista de tweets
list_replys = replys["reply_text"].tolist() #transformando replys do df em lista de replys

for i in range(len(list_tweet_replys)):
  pair_replys.append({"tweet_1":  list_replys[i], "tweet_2": list_tweet_replys[i], "Class": 1, "Conflict": np.nan})

pair_replys_df = pd.DataFrame(pair_replys)
pair_replys_df

,tweet_1,tweet_2,Class,Conflict
0,Vocês também estão sentindo que o clima aqui n...,Comunista defendendo a censura. Nada de novo p...,1,NaN
1,O tiranete Alexandre de Moraes passou de todos...,Eu não consigo ler isso sem passar raiva desse...,1,NaN
2,O tiranete Alexandre de Moraes passou de todos...,"Isso é total ditadura!! Mas e o executivo , nã...",1,NaN
3,"Hoje, 24/07, Fakhoury e demais investigados pe...","... o PGR, Augusto Aras, já opinou pela conces...",1,NaN
4,É verdade que o Twitter derrubou várias contas...,"Dessa vez a culpa não foi do Twitter, e sim do...",1,NaN
...,...,...,...,...
5699,#BOBJEFF Temos que lutar para que a luz da de...,"Estamos de saco cheio de falar, escrever e não...",1,NaN
5700,Não há como aceitar a censura. Não há como ace...,Acabei de receber um aviso do twitter relatand...,1,NaN
5701,LAMENTÁVEL ! Postura ditatorial e autoritária ...,"Censura relativa, ele fez questão de dizer e f...",1,NaN
5702,Quanto você pensa que os ministros do STF não ...,"Esse Lulu boquinha de veludo é uma piada, a f...",1,NaN
5703,"- Agora, no Brasil, é crime criticar e questio...",O pior da história!!! #STFVergonhaNacional Qu...,1,NaN

In [ ]:
for i in range(10):
  #printando na ordem - Replied tweet - tweet_original
  print(f'Tweet_1: {pair_replys_df.iloc[i]["tweet_1"]}')
  print(f'Tweet_2: {pair_replys_df.iloc[i]["tweet_2"]}')
  print()

Tweet_1: Vocês também estão sentindo que o clima aqui no Twitter deu uma melhorada?
Tweet_2: Comunista defendendo a censura. Nada de novo por aqui.

Tweet_1: O tiranete Alexandre de Moraes passou de todos os limites. Ele agora decide sozinho qual informação pode circular no país? Ele decide quem fala e quem cala a boca? Ou os democratas reagem agora a este ato de censura s/ precedentes ou não podem mais falar em liberdade de expressão
Tweet_2: Eu não consigo ler isso sem passar raiva desse fdp!!! É isso mesmo que ele é: um FDP!!! Da pior espécie!!!

Tweet_1: O tiranete Alexandre de Moraes passou de todos os limites. Ele agora decide sozinho qual informação pode circular no país? Ele decide quem fala e quem cala a boca? Ou os democratas reagem agora a este ato de censura s/ precedentes ou não podem mais falar em liberdade de expressão
Tweet_2: Isso é total ditadura!! Mas e o executivo , não vai falar nada?? Este "ministro" do STF é um  CANALHA! #STFVergonhaNacional

Tweet_1: Hoje, 24/07, Fakhoury e demais investigados pelo inquérito das “fake news” foram surpreendidos com a suspensão de suas contas em redes sociais. Já existe um Habeas Corpus contra o ato praticado pelo Ministro Alexandre de Moraes sob a relatoria do Ministro Edson Fachin ...
Tweet_2: ... o PGR, Augusto Aras, já opinou pela concessão da ordem pleiteada para que seja desbloqueado os perfis de Fakhoury das redes sociais. A medida de bloqueio acarreta verdadeira censura por impedir a manifestação do pensamento de Fakhoury...

Tweet_1: É verdade que o Twitter derrubou várias contas de direita, entre elas: Roberto Jefferson, Allan dos Santos, Bernardo Kuster, Sara Winter... ?
Tweet_2: Dessa vez a culpa não foi do Twitter, e sim do #STFVergonhaNacional

Tweet_1: Várias contas foram retidas do Twitter sob a justificativa de "demanda legal". , ,  e outros, todos defensores do governo e críticos do STF. Do que se trata? Não foram notificados de nada ainda. É o tal inquérito ilegal? Isso é censura!
Tweet_2: CENSURA descarada! " Tomar o poder é diferente de ganhar eleicao" disse o ex guerrilheiro de extrema-esquerda... #STFNaoVaiNosCalar

Tweet_1: Podemos até usar este truque, mas precisamos lutar pela nossa liberdade de expressão! #VozParaBernardoKuster
Tweet_2: Concordo, não podemos nos confirmar #VozParaBernardoKuster

Tweet_1: Contei na abertura do 360: no último dia 22, o ministro Alexandre de Moraes deu 24 h para as redes sociais cumprirem a ordem judicial dada em MAIO. Ele tbm estabeleceu multa de R$ 20 mil por endereço que não fosse retirado do ar. #cnn360
Tweet_2: Em contrapartida, a  dá espaço para o Roberto Jefferson continuar a atacar, caluniar e difamar seus desafetos de ocasião.  Diz muito sobre essa emissora.

Tweet_1: ... o PGR, Augusto Aras, já opinou pela concessão da ordem pleiteada para que seja desbloqueado os perfis de Fakhoury das redes sociais. A medida de bloqueio acarreta verdadeira censura por impedir a manifestação do pensamento de Fakhoury...
Tweet_2: ...garantida pelo amplo sistema de liberdade de expressão.O STF já conferiu entendimento de que a liberdade de expressão goza de posição preferencial.Gritante a violação ao direito e livre manifestação pensamento com o bloqueio de contas das redes sociais, uma triste censura!!!

Tweet_1: Liberdade de expressão! #VozParaBernardoKuster
Tweet_2: Não vão calar a direita. #VozParaBernardoKuster

In [ ]:
#convertendo para csv
pair_replys_df.to_csv("contas_suspensas_pares_reply.csv", index=False, encoding="utf-8")
files.download("contas_suspensas_pares_reply.csv")

# **Pares Quote-Tweet**

In [ ]:
#filtrando apenas quotes cujos tweets respondidos foram encontrados no dataset
quoteds = df.loc[(df["is_quote"] == True) & (df["quoted_text"].notna())]
quoteds

,tweet_id,user_id_original,text,created_at_original,retweet_count,like_count,is_retweet,retweeter_user_id,retweet_created_at,is_quote,quoted_tweet_id,quoted_user_id,quoted_text,is_reply,reply_to_tweet_id,reply_to_user_id,reply_to_screen_name,reply_text,class
22,1286738401211887616,884493009840218114,...E a Democracia aos poucos vai se tornando r...,Fri Jul 24 19:01:55 +0000 2020,9,16,True,1.264896e+18,Fri Jul 24 19:20:12 +0000 2020,True,1.286734e+18,1.811268e+08,Corda pra se enforcar! #STFVergonhaNacional #...,False,NaN,NaN,NaN,NaN,2
26,1286743005395902466,1044567268527681536,#VozParaBernardoKuster #STFVergonhaNacional M...,Fri Jul 24 19:20:13 +0000 2020,0,0,False,NaN,NaN,True,1.286735e+18,3.092434e+09,Mude a localização para acessar meus tweets: 1...,False,NaN,NaN,NaN,NaN,2
30,1286741998469349377,2847072890,"Até quando iremos assistir inertes, atitudes a...",Fri Jul 24 19:16:13 +0000 2020,4,10,True,8.673891e+17,Fri Jul 24 19:20:14 +0000 2020,True,1.286713e+18,1.090292e+18,#URGENTE: Após pedido de Alexandre de Moraes (...,False,NaN,NaN,NaN,NaN,2
50,1286743025696346117,1242987831611531272,"Daqui do EUA, eu sigo o Bernardo! #VozParaBern...",Fri Jul 24 19:20:18 +0000 2020,0,0,False,NaN,NaN,True,1.094405e+18,3.092434e+09,Já cancelou sua assinatura na grande mídia hoj...,False,NaN,NaN,NaN,NaN,2
54,1286726401455005697,162453393,Mas não tenha NENHUMA DÚVIDA disso. Seria um g...,Fri Jul 24 18:14:14 +0000 2020,27,275,True,1.258255e+18,Fri Jul 24 19:20:20 +0000 2020,True,1.286724e+18,2.396425e+09,"Podem ter certeza, se fosse a conta do Nando M...",False,NaN,NaN,NaN,NaN,2
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
51505,1287126326206398465,21189671,"Não se fala mais em caixa preta do BNDES, né?",Sat Jul 25 20:43:24 +0000 2020,0,0,False,NaN,NaN,True,1.287030e+18,1.954746e+08,Exclusivo: Luciano Hang obteve 55 empréstimos ...,False,NaN,NaN,NaN,NaN,2
51506,1287126327737360385,958139679810969601,"E se nada for feito, é daí para pior.",Sat Jul 25 20:43:24 +0000 2020,0,0,False,NaN,NaN,True,1.286794e+18,9.793900e+17,A liberdade de expressão no Brasil está no cor...,False,NaN,NaN,NaN,NaN,2
51509,1287126350948597760,1117786210766938114,O estado mínimo que o papagaio quer é só para ...,Sat Jul 25 20:43:30 +0000 2020,0,0,False,NaN,NaN,True,1.287030e+18,1.954746e+08,Exclusivo: Luciano Hang obteve 55 empréstimos ...,False,NaN,NaN,NaN,NaN,2
51513,1287126433349931008,1129526345954975745,Tomara que dê certo,Sat Jul 25 20:43:50 +0000 2020,0,0,False,NaN,NaN,True,1.287111e+18,1.591895e+07,"Por meio de nota pública, membros do MP Pró-So...",False,NaN,NaN,NaN,NaN,2
51516,1287126460243873793,218276449,A escalada de Hang escancara a triste realidad...,Sat Jul 25 20:43:56 +0000 2020,0,0,False,NaN,NaN,True,1.287030e+18,1.954746e+08,Exclusivo: Luciano Hang obteve 55 empréstimos ...,False,NaN,NaN,NaN,NaN,2

In [ ]:
#Gerando pares (por quote)
pair_quote = [] #lista de dicionario que irá armazenar os pares
list_tweet_quote = quoteds["text"].tolist() #transformando tweets do df em lista de tweets
list_quote = quoteds["quoted_text"].tolist() #transformando quote do df em lista de quotes

for i in range(len(list_tweet_quote)):
  pair_quote.append({"tweet_1": list_quote[i], "tweet_2": list_tweet_quote[i] , "Class": 2, "Conflict": np.nan})

pair_quote_df = pd.DataFrame(pair_quote)
pair_quote_df

,tweet_1,tweet_2,Class,Conflict
0,Corda pra se enforcar! #STFVergonhaNacional #...,...E a Democracia aos poucos vai se tornando r...,2,NaN
1,Mude a localização para acessar meus tweets: 1...,#VozParaBernardoKuster #STFVergonhaNacional M...,2,NaN
2,#URGENTE: Após pedido de Alexandre de Moraes (...,"Até quando iremos assistir inertes, atitudes a...",2,NaN
3,Já cancelou sua assinatura na grande mídia hoj...,"Daqui do EUA, eu sigo o Bernardo! #VozParaBern...",2,NaN
4,"Podem ter certeza, se fosse a conta do Nando M...",Mas não tenha NENHUMA DÚVIDA disso. Seria um g...,2,NaN
...,...,...,...,...
16156,Exclusivo: Luciano Hang obteve 55 empréstimos ...,"Não se fala mais em caixa preta do BNDES, né?",2,NaN
16157,A liberdade de expressão no Brasil está no cor...,"E se nada for feito, é daí para pior.",2,NaN
16158,Exclusivo: Luciano Hang obteve 55 empréstimos ...,O estado mínimo que o papagaio quer é só para ...,2,NaN
16159,"Por meio de nota pública, membros do MP Pró-So...",Tomara que dê certo,2,NaN
16160,Exclusivo: Luciano Hang obteve 55 empréstimos ...,A escalada de Hang escancara a triste realidad...,2,NaN

In [ ]:
for i in range(10):
  #printando na ordem - Quoted tweet - tweet
  print(f'Tweet_1: {pair_quote_df.iloc[i]["tweet_1"]}')
  print(f'Tweet_2: {pair_quote_df.iloc[i]["tweet_2"]}')
  print()

Tweet_1: Corda pra se enforcar! #STFVergonhaNacional  #BolsonaroOrgulhoDoBrasil  URGENTE: ALEXANDRE DE MORAES DETERMINA SUSPENSÃO DE CONTAS NO TWITTER DE APOIADORES DE BOLSONARO
Tweet_2: ...E a Democracia aos poucos vai se tornando refém de um Poder que existe para, em tese, salvaguardar a Constituição, cujo colegiado se perpetua na função sem ter recebido um voto sequer daquele de onde o poder Constitucional originalmente emana: O POVO!...

Tweet_1: Mude a localização para acessar meus tweets: 1. Vá em Conta e Privacidade, 2. Clique em Conta, 3. Depois em Dados e Permissões, 4. E mude sua localização para os EUA. Aí você acompanha meus Tweets normalmente. Tente censurar o Tio Sam agora, Cabeça de Ovo! #VozParaBernardoKuster
Tweet_2: #VozParaBernardoKuster #STFVergonhaNacional  Mude sua localização para Estados Unidos, terra tio San cabeça de ovo não manda.

Tweet_1: #URGENTE: Após pedido de Alexandre de Moraes (STF), o Twitter derrubou a conta de Sara Winter, Roberto Jefferson, Allan dos Santos, Bernardo Küster e Luciano Hang e outros foram vítimas da censura com base no inquérito ilegal das fake news.
Tweet_2: Até quando iremos assistir inertes, atitudes arbitrárias querendo calar nossa liberdade de pensamento e expressão?

Tweet_1: Já cancelou sua assinatura na grande mídia hoje?  Estadão: 0800 014 7720 Folha: 0800 140 090 Globo: 0800 881 8000 Veja: 0800 775 2112  ISTOÉ: 0800 888 2111
Tweet_2: Daqui do EUA, eu sigo o Bernardo! #VozParaBernardoKuster

Tweet_1: Podem ter certeza, se fosse a conta do Nando Moura, FMB, Andreazza, Vera Magalhães, seja por qual motivo fosse, que tivesse sido bloqueada nas redes sociais pelo STF, o gado estaria comemorando.
Tweet_2: Mas não tenha NENHUMA DÚVIDA disso. Seria um grande dia  pra eles.   Eu acho muito perigoso tudo o que está acontecendo, e espero q exista algum embasamento realmente sério que justifique essa queda de perfis. Pq até agora é só fumaça.

Tweet_1: Twitter derruba contas bolsonarista  Roberto Jefferson, presidente do PTB   Luciano Hang, empresário  Edgard Corona, empresário  Otávio Fakhoury, empresário  Bernardo Küster  Allan dos Santos, blogueiro  Winston Rodrigues Lima  Reynaldo Bianchi  Sara Giromini Enzo Leonardo
Tweet_2: A nata do bolsonarismo

Tweet_1: Em nota à imprensa após suspensão de perfis pró-Bolsonaro, o Twitter disse que "agiu estritamente em cumprimento a uma ordem legal proveniente de inquérito do Supremo Tribunal Federal (STF)".
Tweet_2: "Ordem legal" baseada em lei nenhuma e com um inquérito que todos desconhecem o conteúdo. Se a oposição soubesse que seria tão fácil CENSURA, acho que nem teriam se dado ao trabalho de articular pra tentar emplacar essa PL 2630/2020.

Tweet_1: Alexandre determina e Twitter bloqueia perfis do presidente do PTB, Roberto Jefferson, dos empresários Luciano Hang, Edgard Corona, Otávio Fakhoury, Bernardo Küster, além do jornalista Allan dos Santos e do assessor do deputado estadual de São Paulo Edson Salomão.
Tweet_2: Eu não consigo ler isso sem passar raiva desse fdp!!! É isso mesmo que ele é: um FDP!!! Da pior espécie!!!

Tweet_1: Alexandre determina e Twitter bloqueia perfis do presidente do PTB, Roberto Jefferson, dos empresários Luciano Hang, Edgard Corona, Otávio Fakhoury, Bernardo Küster, além do jornalista Allan dos Santos e do assessor do deputado estadual de São Paulo Edson Salomão.
Tweet_2: Generais, sejam patriotas fechem logo esse stf e renovem essa instituição. O congresso Nacional também tem que ser fechado.  Não aguento mais tanta canalhice.

Tweet_1: SEXTA FEIRA É DIA DA GRANDE FINAL DO SUB 18. SEXTA FEIRA TAMBÉM É  DIA DA NOSSA TORCIDA DA UM SHOW NAS ARQUIBANCADAS !   #AVANTEPÇA  #TJP #MENINOSDAPRAÇA
Tweet_2: vamos ser campeão

In [ ]:
#convertendo para csv
pair_quote_df.to_csv("contas_suspensas_pares_quote.csv", index=False, encoding="utf-8")
files.download("contas_suspensas_pares_quote.csv")

In [ ]:
#concatenando os datasets parciais:
df_contas_suspensas = pd.concat([pair_generics_df, pair_replys_df, pair_quote_df], ignore_index=True, axis = 0)
df_contas_suspensas

,tweet_1,tweet_2,Class,Conflict
0,Guilherme Fiuza diz que Alexandre de Moraes nã...,Boletim das 17h01 do dia 24/07/2020 Situação ...,0,NaN
1,peço perdao pessoal nao e do meu feitio defend...,TWITTER DERRUBA CONTAS DOS DISSEMINADORES DE F...,0,NaN
2,Vejam agora no programa PINGO NOS IS o Roberto...,"Mano, grande mídia é muito fraquinha, mesmo Os...",0,NaN
3,Roberto Jefferson acaba de afirmar no Terça Li...,grande dia difícil,0,NaN
4,qual a sua Opniao sobre a Censura nas redes s...,ROBERTO JEFFERSON DENUNCIA PERFIL FALSO EM SEU...,0,NaN
...,...,...,...,...
31860,Exclusivo: Luciano Hang obteve 55 empréstimos ...,"Não se fala mais em caixa preta do BNDES, né?",2,NaN
31861,A liberdade de expressão no Brasil está no cor...,"E se nada for feito, é daí para pior.",2,NaN
31862,Exclusivo: Luciano Hang obteve 55 empréstimos ...,O estado mínimo que o papagaio quer é só para ...,2,NaN
31863,"Por meio de nota pública, membros do MP Pró-So...",Tomara que dê certo,2,NaN
31864,Exclusivo: Luciano Hang obteve 55 empréstimos ...,A escalada de Hang escancara a triste realidad...,2,NaN

In [ ]:
#convertendo para csv
df_contas_suspensas.to_csv("contas_suspensas_pares.csv", index=False, encoding="utf-8")
files.download("contas_suspensas_pares.csv")