# **Projeto de Graduação em Computação II [2026-Q1]**

Universidade Federal do ABC

Orientador Carlos da Silva dos Santos

### **EQUIPE**

---

Caio Cardoso Dos Santos - RA: 11202021632

Victor Ravazio de Lima - RA: 11201920941

### **IMPLEMENTAÇÃO**
---

In [1]:
# modulo para importar dataset a partir de um link
!pip install gdown

Requirement already satisfied: gdown in /usr/local/lib/python3.12/dist-packages (5.2.1)
Requirement already satisfied: beautifulsoup4 in /usr/local/lib/python3.12/dist-packages (from gdown) (4.13.5)
Requirement already satisfied: filelock in /usr/local/lib/python3.12/dist-packages (from gdown) (3.25.2)
Requirement already satisfied: requests[socks] in /usr/local/lib/python3.12/dist-packages (from gdown) (2.32.4)
Requirement already satisfied: tqdm in /usr/local/lib/python3.12/dist-packages (from gdown) (4.67.3)
Requirement already satisfied: soupsieve>1.2 in /usr/local/lib/python3.12/dist-packages (from beautifulsoup4->gdown) (2.8.3)
Requirement already satisfied: typing-extensions>=4.0.0 in /usr/local/lib/python3.12/dist-packages (from beautifulsoup4->gdown) (4.15.0)
Requirement already satisfied: charset_normalizer<4,>=2 in /usr/local/lib/python3.12/dist-packages (from requests[socks]->gdown) (3.4.7)
Requirement already satisfied: idna<4,>=2.5 in /usr/local/lib/python3.12/dist-packages (from requests[socks]->gdown) (3.11)
Requirement already satisfied: urllib3<3,>=1.21.1 in /usr/local/lib/python3.12/dist-packages (from requests[socks]->gdown) (2.5.0)
Requirement already satisfied: certifi>=2017.4.17 in /usr/local/lib/python3.12/dist-packages (from requests[socks]->gdown) (2026.2.25)
Requirement already satisfied: PySocks!=1.5.7,>=1.5.6 in /usr/local/lib/python3.12/dist-packages (from requests[socks]->gdown) (1.7.1)

In [2]:
#Bibliotecas
import pandas as pd
import numpy as np
from google.colab import files
import gdown
import matplotlib.pyplot as plt
import random

In [3]:
# baixando dataset para o collab
import gdown

file_id = "1iT71SnoppcnZ3UFKf5LiT-v3FQ42_6rd"
url = f"https://drive.google.com/uc?id={file_id}"

gdown.download(url, "aborto.csv", quiet=False)

Downloading...
From: https://drive.google.com/uc?id=1iT71SnoppcnZ3UFKf5LiT-v3FQ42_6rd
To: /content/aborto.csv
100%|██████████| 4.41M/4.41M [00:00<00:00, 15.5MB/s]

'aborto.csv'

In [4]:
#carregando o dataset
df = pd.read_csv ("aborto.csv")
df.head()

,tweet_id,user_id_original,text,created_at_original,retweet_count,like_count,is_retweet,retweeter_user_id,retweet_created_at,is_quote,quoted_tweet_id,quoted_user_id,quoted_text,is_reply,reply_to_tweet_id,reply_to_user_id,reply_to_screen_name,reply_text,class
0,1250542322313560064,1053003526052474881,"STF, o câncer do Brasil, agora quer decidir qu...",Wed Apr 15 21:51:38 +0000 2020,54,85,True,1.015739e+18,Wed Apr 15 22:56:26 +0000 2020,False,NaN,NaN,NaN,False,NaN,NaN,NaN,NaN,0
1,1250524480134361089,3062568484,#AbortoNAO é da sua conta se o corpo nao é se...,Wed Apr 15 20:40:44 +0000 2020,246,736,True,1.073292e+18,Wed Apr 15 22:56:26 +0000 2020,False,NaN,NaN,NaN,False,NaN,NaN,NaN,NaN,0
2,1250558630656704517,1044570099074650112,Alô STF... repitam comigo: #AbortoNao,Wed Apr 15 22:56:26 +0000 2020,0,0,False,NaN,NaN,False,NaN,NaN,NaN,False,NaN,NaN,NaN,NaN,0
3,1250531402355036165,1087259768,STF quer aplicar a medida enquanto a gente não...,Wed Apr 15 21:08:14 +0000 2020,1436,4040,True,8.776809e+07,Wed Apr 15 22:56:26 +0000 2020,False,NaN,NaN,NaN,False,NaN,NaN,NaN,NaN,0
4,1250550843599970308,350476403,"O que a Bíblia fala sobre o aborto? ""Antes qu...",Wed Apr 15 22:25:29 +0000 2020,144,418,True,1.221111e+18,Wed Apr 15 22:56:26 +0000 2020,False,NaN,NaN,NaN,False,NaN,NaN,NaN,NaN,0

In [5]:
#numero total de instancias no dataset
df.shape

(15382, 19)

In [6]:
df

,tweet_id,user_id_original,text,created_at_original,retweet_count,like_count,is_retweet,retweeter_user_id,retweet_created_at,is_quote,quoted_tweet_id,quoted_user_id,quoted_text,is_reply,reply_to_tweet_id,reply_to_user_id,reply_to_screen_name,reply_text,class
0,1250542322313560064,1053003526052474881,"STF, o câncer do Brasil, agora quer decidir qu...",Wed Apr 15 21:51:38 +0000 2020,54,85,True,1.015739e+18,Wed Apr 15 22:56:26 +0000 2020,False,NaN,NaN,NaN,False,NaN,NaN,NaN,NaN,0
1,1250524480134361089,3062568484,#AbortoNAO é da sua conta se o corpo nao é se...,Wed Apr 15 20:40:44 +0000 2020,246,736,True,1.073292e+18,Wed Apr 15 22:56:26 +0000 2020,False,NaN,NaN,NaN,False,NaN,NaN,NaN,NaN,0
2,1250558630656704517,1044570099074650112,Alô STF... repitam comigo: #AbortoNao,Wed Apr 15 22:56:26 +0000 2020,0,0,False,NaN,NaN,False,NaN,NaN,NaN,False,NaN,NaN,NaN,NaN,0
3,1250531402355036165,1087259768,STF quer aplicar a medida enquanto a gente não...,Wed Apr 15 21:08:14 +0000 2020,1436,4040,True,8.776809e+07,Wed Apr 15 22:56:26 +0000 2020,False,NaN,NaN,NaN,False,NaN,NaN,NaN,NaN,0
4,1250550843599970308,350476403,"O que a Bíblia fala sobre o aborto? ""Antes qu...",Wed Apr 15 22:25:29 +0000 2020,144,418,True,1.221111e+18,Wed Apr 15 22:56:26 +0000 2020,False,NaN,NaN,NaN,False,NaN,NaN,NaN,NaN,0
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
15377,1250878804639322112,1222107818054033408,Calma cadelinha d Soros Perdeu a linha Pegou g...,Thu Apr 16 20:08:41 +0000 2020,0,0,False,NaN,NaN,False,NaN,NaN,NaN,True,1.250877e+18,1.112839e+18,smaaxe,NaN,1
15378,1250878960520572931,765543343581528064,é um direito sim! Mais vale abortar logo do qu...,Thu Apr 16 20:09:19 +0000 2020,0,0,False,NaN,NaN,True,1.250788e+18,605414528.0,Já que tenho útero posso opinar. Aborto é imor...,False,NaN,NaN,NaN,NaN,2
15379,1250878992175030278,709698858,Esses dois são judeus? Não sabia,Thu Apr 16 20:09:26 +0000 2020,0,0,False,NaN,NaN,True,1.250861e+18,172572347.0,S/ aborto e eventual voto de Fux e Barroso: a...,False,NaN,NaN,NaN,NaN,2
15380,1250879142687584261,1222610949728886785,"No dia 24, na próxima semana, o STF vai votar ...",Thu Apr 16 20:10:02 +0000 2020,0,0,False,NaN,NaN,False,NaN,NaN,NaN,False,NaN,NaN,NaN,NaN,0
15381,1250528187911680001,975127727501185025,"Bora subir, robozada? #AbortoNao",Wed Apr 15 20:55:28 +0000 2020,4399,17162,False,NaN,NaN,False,NaN,NaN,NaN,False,NaN,NaN,NaN,NaN,0

In [7]:
df[df['reply_text'].str.contains('eu vendo a #AbortoNAO subir e lembrando dessas', na=False)]

Empty DataFrame
Columns: [tweet_id, user_id_original, text, created_at_original, retweet_count, like_count, is_retweet, retweeter_user_id, retweet_created_at, is_quote, quoted_tweet_id, quoted_user_id, quoted_text, is_reply, reply_to_tweet_id, reply_to_user_id, reply_to_screen_name, reply_text, class]
Index: []

In [8]:
#classe 0
sum_class_0 = int ((df['class'] == 0).sum())
sum_class_0

8146

In [9]:
#Classe 1
sum_class_1 = int ((df['class'] == 1).sum())
sum_class_1

4191

In [10]:
#classe 2
sum_class_2 = int ((df['class'] == 2).sum())
sum_class_2

3045

In [11]:
#numero de tweets genericos (não é quote nem reply)
generics = df.loc[(df["is_quote"] == False) & (df["is_reply"] == False)]
generics.shape[0]

8146

In [12]:
#numero de tweets replys totais (com e sem respostas os respectivos tweets originais obtidos)
replys_tot = df.loc[df["is_reply"] == True]
replys_tot.shape[0]

4232

In [13]:
#numero de tweets replys com respostas encontradas
replys = df.loc[(df["is_reply"]) & (df["reply_text"].notna())]
replys.shape[0]

1729

In [14]:
#numero de quotes
quoteds_tot = df.loc[df["is_quote"] == True]
quoteds_tot.shape[0]

3045

In [15]:
#numero de quotes usaveis
quoteds = df.loc[(df["is_quote"] == True) & (df["quoted_text"].notna())]
quoteds.shape[0]

3028

In [16]:
#intersecções entre quotes e replys
replys_quotes = df.loc[(df["is_reply"] == True) & (df["is_quote"] == True)]
replys_quotes.shape[0]

41

In [17]:
tot = generics.shape[0] + replys_tot.shape[0] + quoteds_tot.shape[0] - replys_quotes.shape[0]
tot

15382

In [18]:
replys_tot.head()

,tweet_id,user_id_original,text,created_at_original,retweet_count,like_count,is_retweet,retweeter_user_id,retweet_created_at,is_quote,quoted_tweet_id,quoted_user_id,quoted_text,is_reply,reply_to_tweet_id,reply_to_user_id,reply_to_screen_name,reply_text,class
11,1250558640559403009,1084214953463160833,#AbortoNAO - Hahahha.... tipico... Você adot...,Wed Apr 15 22:56:28 +0000 2020,0,0,False,NaN,NaN,False,NaN,NaN,NaN,True,1.250552e+18,1.024074e+18,gabs__mo,NaN,1
14,1250558643692544000,1221147589564944385,"VC não acha melhor a bebê nascer não, vai ter ...",Wed Apr 15 22:56:29 +0000 2020,0,0,False,NaN,NaN,False,NaN,NaN,NaN,True,1.250534e+18,1.116913e+18,CoralinaCris,NaN,1
15,1250558644283990017,1223017902586105857,"Pra abrir as pernas requer responsabilidade, a...",Wed Apr 15 22:56:29 +0000 2020,0,0,False,NaN,NaN,False,NaN,NaN,NaN,True,1.250558e+18,1.123022e+18,SABRINA73009145,NaN,1
27,1250558657739345922,897894817681858560,#AbortoNAO vida sim,Wed Apr 15 22:56:32 +0000 2020,0,0,False,NaN,NaN,False,NaN,NaN,NaN,True,1.250528e+18,9.751277e+17,CarlaZambelli38,"Bora subir, robozada? #AbortoNao",1
30,1250558661937766401,1189604917020889088,Que Porra é essa ? #AbortoNao,Wed Apr 15 22:56:33 +0000 2020,0,0,False,NaN,NaN,False,NaN,NaN,NaN,True,1.250531e+18,1.087260e+09,taoquei1,STF quer aplicar a medida enquanto a gente não...,1

# **Pares Tweets genéricos**

In [19]:
generics = df.loc[(df["is_quote"] == False) & (df["is_reply"] == False)]
generics

,tweet_id,user_id_original,text,created_at_original,retweet_count,like_count,is_retweet,retweeter_user_id,retweet_created_at,is_quote,quoted_tweet_id,quoted_user_id,quoted_text,is_reply,reply_to_tweet_id,reply_to_user_id,reply_to_screen_name,reply_text,class
0,1250542322313560064,1053003526052474881,"STF, o câncer do Brasil, agora quer decidir qu...",Wed Apr 15 21:51:38 +0000 2020,54,85,True,1.015739e+18,Wed Apr 15 22:56:26 +0000 2020,False,NaN,NaN,NaN,False,NaN,NaN,NaN,NaN,0
1,1250524480134361089,3062568484,#AbortoNAO é da sua conta se o corpo nao é se...,Wed Apr 15 20:40:44 +0000 2020,246,736,True,1.073292e+18,Wed Apr 15 22:56:26 +0000 2020,False,NaN,NaN,NaN,False,NaN,NaN,NaN,NaN,0
2,1250558630656704517,1044570099074650112,Alô STF... repitam comigo: #AbortoNao,Wed Apr 15 22:56:26 +0000 2020,0,0,False,NaN,NaN,False,NaN,NaN,NaN,False,NaN,NaN,NaN,NaN,0
3,1250531402355036165,1087259768,STF quer aplicar a medida enquanto a gente não...,Wed Apr 15 21:08:14 +0000 2020,1436,4040,True,8.776809e+07,Wed Apr 15 22:56:26 +0000 2020,False,NaN,NaN,NaN,False,NaN,NaN,NaN,NaN,0
4,1250550843599970308,350476403,"O que a Bíblia fala sobre o aborto? ""Antes qu...",Wed Apr 15 22:25:29 +0000 2020,144,418,True,1.221111e+18,Wed Apr 15 22:56:26 +0000 2020,False,NaN,NaN,NaN,False,NaN,NaN,NaN,NaN,0
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
15367,1250878057629573120,3361836244,resultado das minhas discussões com os pró-vid...,Thu Apr 16 20:05:43 +0000 2020,0,0,False,NaN,NaN,False,NaN,NaN,NaN,False,NaN,NaN,NaN,NaN,0
15369,1250878116878323714,4204194933,#AbortoSim homem não tem direito a opinião sob...,Thu Apr 16 20:05:57 +0000 2020,0,0,False,NaN,NaN,False,NaN,NaN,NaN,False,NaN,NaN,NaN,NaN,0
15375,1250878695981617152,803792362598178822,#STFVergonhaNacional tão precisando estudar ma...,Thu Apr 16 20:08:15 +0000 2020,0,0,False,NaN,NaN,False,NaN,NaN,NaN,False,NaN,NaN,NaN,NaN,0
15380,1250879142687584261,1222610949728886785,"No dia 24, na próxima semana, o STF vai votar ...",Thu Apr 16 20:10:02 +0000 2020,0,0,False,NaN,NaN,False,NaN,NaN,NaN,False,NaN,NaN,NaN,NaN,0
15381,1250528187911680001,975127727501185025,"Bora subir, robozada? #AbortoNao",Wed Apr 15 20:55:28 +0000 2020,4399,17162,False,NaN,NaN,False,NaN,NaN,NaN,False,NaN,NaN,NaN,NaN,0

In [20]:
#gerando pares de tweets generico - Por amostra
sample_size = 10000
pair_generics = [] #lista de dicionario correspondente aos pares
list_tweet_generics = generics["text"].tolist() #transformando tweets em lista

for i in range(sample_size):
  pair_gen = random.sample(list_tweet_generics, 2)
  pair_generics.append({"tweet_1": pair_gen[0], "tweet_2": pair_gen[1], "Class": 0, "Conflict": np.nan})

pair_generics_df = pd.DataFrame(pair_generics) #transformando a lista de dicionarios em df
pair_generics_df

,tweet_1,tweet_2,Class,Conflict
0,"""Fiquem em casa para não morrer de corona víru...",Proteção para os indefesos. Não à cultura de m...,0,NaN
1,"Sou a favor de liberar o aborto, somente o dia...","#AbortoNAO STF SÓ TEM BANDIDO, SAFADOS, CANALH...",0,NaN
2,"#AbortoNao/ ai a criança nasce sendo odiada, s...","tá bom pró-vidas, agora me expliquem a lógica:...",0,NaN
3,Quem foi o eleitor do bozonaro Que criou as t...,"#AbortoSim um caralho, você mulher é dona sim ...",0,NaN
4,"se não é seu corpo, não é você quem decide. #A...","Uma mulher abortista, poderia ter sido abortad...",0,NaN
...,...,...,...,...
9995,Não existe discussão com quem defende aborto. ...,ver a esquerda com a # ao co trario dessa........,0,NaN
9996,Em tempos de pregar o amor ao próximo e a pres...,#AbortoSim ??? E o #FiquemEmCasa pra salvar v...,0,NaN
9997,#AbortoNao #AbortoSim se a opinião com a relig...,""" vamos zelar pelas vidas durante a pandemia ...",0,NaN
9998,Apenas #AbortoSim,#AbortoNao só to vendo um monte de homen branc...,0,NaN
9999,e vamos de #AbortoSim,"A vida gerada, não pertence a pessoa que a est...",0,NaN

In [21]:
#exibindo uma pequena amostra

for i in range(10):
  #printando na ordem - Replied tweet - tweet_original
  print(f'Tweet_1: {pair_generics_df.iloc[i]["tweet_1"]}')
  print(f'Tweet_2: {pair_generics_df.iloc[i]["tweet_2"]}')
  print()

Tweet_1: "Fiquem em casa para não morrer de corona vírus, a não ser se for pra abortar aí sim ou se você for um aborto, pode sair da casinha"  HIPOCRISIA é falar pra ficar preso em casa pra muitas pessoas não morrer e querer assassinar um ser tão inocente   HIPOCRISIA É FODA!! #AbortoSIM
Tweet_2: Proteção para os indefesos. Não à cultura de morte. #AbortoNao

Tweet_1: Sou a favor de liberar o aborto, somente o dia que estuprador, ladrão, assassinos e políticos corruptos forem condenados a pena de morte em praça pública! Já que é pra matar, isso também tem que valer! Apesar minha opinião. #AbortoNao  Alguém discorda?
Tweet_2: #AbortoNAO STF SÓ TEM BANDIDO, SAFADOS, CANALHAS. DIGA NÃO AO ABORTO.

Tweet_1: #AbortoNao/ ai a criança nasce sendo odiada, sendo rejeitada ou apanhando e fica com o psicológico fodido ou a mãe vai  entrega pra adoção e ajuda a lotar mais um orfanato e talvez a criança nunca seja adotada  É melhor deixar uma criança sofrendo sozinha no mundo doq nem deixar+
Tweet_2: tá bom pró-vidas, agora me expliquem a lógica: forçar a gravidez de outra pessoa só pra não 'matar' uma vida inocente e ter futuramente mais uma criança ou abandonada, ou passando fome, ou pelas ruas e sem abrigo. sem útero sem opinião e mesmo se tiver, foca no teu.  #AbortoNao

Tweet_1: Quem foi o eleitor do bozonaro  Que criou as tag #BabuVitimista e #AbortoNao ???
Tweet_2: #AbortoSim um caralho, você mulher é dona sim do seu corpo, então trate de usar camisinha e se cuidar! Nenhuma vida deve pagar por uma irresponsabilidade que você não teve e não quer assumir, a não ser que vc tenha sido abusada!

Tweet_1: se não é seu corpo, não é você quem decide. #AbortoSim
Tweet_2: Uma mulher abortista, poderia ter sido abortada. Ou seja, assassinada.  E não faria essa campanha que é crime contra a vida. A arte de se colocar no lugar. #AbortoNao Obs: nos casos já previstos de alto risco de morte no parto, ou crime de estupro, sou a favor.

Tweet_1: Eu estava aqui matutando, de que serve o presidente da republica no Brasil? O STF manda de um lado, presidente da Câmara de outro, senado manda fazer ao contrário e no final para que serve o presidente no Brasil? É impossível fazer algo sem os outros se intrometerem. #AbortoNao
Tweet_2: Aborto não é método contraceptivo.  Admitir o aborto além das previsões legais existentes é um estímulo a retirar dos ombros das pessoas a responsabilidade pela prática do sexo.  Não admito q meu imposto custeie o assassinato de bebês inocentes!  #AbortoNao

Tweet_1: MULHER NENHUMA DEVE SER OBRIGADA A DEIXAR DE FAZER A FACULDADE E SEGUIR SUA VIDA POR CAUSA DE UMA CRIANÇA/FETO  #AbortoSim #AbortoSim
Tweet_2: #AbortoSIM #AbortoNao  1. mulheres SEMPRE vão abortar, a questao da legalizaçao do aborto é: dar um apoio psicológico pra mulher antes/durante/após a decisão; e dar acesso SEGURO ao procedimento; a vida e dignidade da mulher.  2. quem mais se f*de com a criminalizaçao (+)

Tweet_1: acho engraçado essa tag #AbortoNao,sendo que a maioria é sobre HOMENS falando kkkkkkkkkkkkkkkkkkkkkkkkkkkkkk ai me dê paciência pq se me dar portal de fala eu parto é pra agressividade.
Tweet_2: mas não disse que me arrependi   Dua Lipa Rihanna Thomas Santana Joji #AbortoNao JUNGKOOK #samsungnobbb Titi #festabbb #Riverdale #عبودكا #instagrammusic #COVID19 #نايف_حمدان  #Apple #restateacasa  sadie #Covid_19

Tweet_1: Sou a favor da legalização do aborto mas essa tag #AbortoSim nos treding topics soa mal, sensacionalistas vão usar pra dizer q somos a favor de assassinato de bebês quando na vdd somos a favor q essa decisão seja da mulher q carrega o feto e q ela tenha segurança no procedimento
Tweet_2: LEGALIZAAAAAA STF DA ESSE DIREITO PARA AS MULHERES POBRES SEM QUE ELAS MORRAM  #AbortoNao

Tweet_1: Se sua mãe pensasse assim vocês Não estariam aqui seus hipócritas #AbortoNao
Tweet_2: Viva e deixe viver!  #AbortoNao

In [22]:
#convertendo para csv
pair_generics_df.to_csv("Aborto_pares_genericos.csv", index=False, encoding="utf-8")
files.download("Aborto_pares_genericos.csv")

# **Pares Tweet-Reply**

In [23]:
#filtrando apenas replys cujos tweets respondidos foram encontrados no dataset
replys = df.loc[(df["is_reply"] == True) & (df["reply_text"].notna())]
replys

,tweet_id,user_id_original,text,created_at_original,retweet_count,like_count,is_retweet,retweeter_user_id,retweet_created_at,is_quote,quoted_tweet_id,quoted_user_id,quoted_text,is_reply,reply_to_tweet_id,reply_to_user_id,reply_to_screen_name,reply_text,class
27,1250558657739345922,897894817681858560,#AbortoNAO vida sim,Wed Apr 15 22:56:32 +0000 2020,0,0,False,NaN,NaN,False,NaN,NaN,NaN,True,1.250528e+18,9.751277e+17,CarlaZambelli38,"Bora subir, robozada? #AbortoNao",1
30,1250558661937766401,1189604917020889088,Que Porra é essa ? #AbortoNao,Wed Apr 15 22:56:33 +0000 2020,0,0,False,NaN,NaN,False,NaN,NaN,NaN,True,1.250531e+18,1.087260e+09,taoquei1,STF quer aplicar a medida enquanto a gente não...,1
34,1250558670515113985,981500141600432129,Assassinato nunca! #AbortoNAO,Wed Apr 15 22:56:35 +0000 2020,0,0,False,NaN,NaN,False,NaN,NaN,NaN,True,1.250539e+18,3.504764e+08,Jouberth19,Enquanto lutamos pela nossa vida contra o covi...,1
45,1250558699573297152,348759234,Vergonha desse STF #AbortoNAO,Wed Apr 15 22:56:42 +0000 2020,0,0,False,NaN,NaN,False,NaN,NaN,NaN,True,1.250531e+18,1.087260e+09,taoquei1,STF quer aplicar a medida enquanto a gente não...,1
55,1250529001875128320,1248766993517477888,Gostaria de informar que devido a grande reper...,Wed Apr 15 20:58:42 +0000 2020,8,54,True,373058006.0,Wed Apr 15 22:56:46 +0000 2020,False,NaN,NaN,NaN,True,1.250528e+18,9.751277e+17,CarlaZambelli38,"Bora subir, robozada? #AbortoNao",1
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
15346,1250876523109851137,1139604720098709505,Quarentena = Cortina de fumaça (ou motorizada ...,Thu Apr 16 19:59:37 +0000 2020,0,0,False,NaN,NaN,False,NaN,NaN,NaN,True,1.250598e+18,1.748182e+08,leandroruschel,Por que a extrema-imprensa esconde do público ...,1
15348,1250876713149612032,2722196369,Os abortistas querem oferecer as crianças nos ...,Thu Apr 16 20:00:23 +0000 2020,0,0,False,NaN,NaN,False,NaN,NaN,NaN,True,1.250861e+18,1.725723e+08,opropriopontes,S/ aborto e eventual voto de Fux e Barroso: a...,1
15352,1250877047980863488,4034757077,#AbortoNao ninguém tem o direito de tirar a vi...,Thu Apr 16 20:01:43 +0000 2020,0,0,False,NaN,NaN,False,NaN,NaN,NaN,True,1.250569e+18,3.504764e+08,Jouberth19,A tag #AbortoNao está em 1º lugar nos trends c...,1
15360,1250877595211743233,582380587,O que é dred scott case? #AbortoNao,Thu Apr 16 20:03:53 +0000 2020,0,0,False,NaN,NaN,False,NaN,NaN,NaN,True,1.250605e+18,1.725723e+08,opropriopontes,STF pode estar cometendo o seu maior erro: pau...,1
15368,1250878098637090816,743132283431981056,Não deveriam ter o dom de fecundar!!! #AbortoNao,Thu Apr 16 20:05:53 +0000 2020,0,0,False,NaN,NaN,False,NaN,NaN,NaN,True,1.250866e+18,1.246908e+18,Madruga002,Concordo com tudo. #AbortoNao,1

In [24]:
replys[replys['reply_text'].str.contains('eu vendo a #AbortoNAO subir e lembrando dessas', na=False)]

Empty DataFrame
Columns: [tweet_id, user_id_original, text, created_at_original, retweet_count, like_count, is_retweet, retweeter_user_id, retweet_created_at, is_quote, quoted_tweet_id, quoted_user_id, quoted_text, is_reply, reply_to_tweet_id, reply_to_user_id, reply_to_screen_name, reply_text, class]
Index: []

In [25]:
#Gerando pares (por reply)
pair_replys = [] #lista de dicionario que irá armazenar os pares
list_tweet_replys = replys["text"].tolist() #transformando tweets do df em lista de tweets
list_replys = replys["reply_text"].tolist() #transformando replys do df em lista de replys

for i in range(len(list_tweet_replys)):
  pair_replys.append({"tweet_1":  list_replys[i], "tweet_2": list_tweet_replys[i], "Class": 1, "Conflict": np.nan})

pair_replys_df = pd.DataFrame(pair_replys)
pair_replys_df

,tweet_1,tweet_2,Class,Conflict
0,"Bora subir, robozada? #AbortoNao",#AbortoNAO vida sim,1,NaN
1,STF quer aplicar a medida enquanto a gente não...,Que Porra é essa ? #AbortoNao,1,NaN
2,Enquanto lutamos pela nossa vida contra o covi...,Assassinato nunca! #AbortoNAO,1,NaN
3,STF quer aplicar a medida enquanto a gente não...,Vergonha desse STF #AbortoNAO,1,NaN
4,"Bora subir, robozada? #AbortoNao",Gostaria de informar que devido a grande reper...,1,NaN
...,...,...,...,...
1724,Por que a extrema-imprensa esconde do público ...,Quarentena = Cortina de fumaça (ou motorizada ...,1,NaN
1725,S/ aborto e eventual voto de Fux e Barroso: a...,Os abortistas querem oferecer as crianças nos ...,1,NaN
1726,A tag #AbortoNao está em 1º lugar nos trends c...,#AbortoNao ninguém tem o direito de tirar a vi...,1,NaN
1727,STF pode estar cometendo o seu maior erro: pau...,O que é dred scott case? #AbortoNao,1,NaN
1728,Concordo com tudo. #AbortoNao,Não deveriam ter o dom de fecundar!!! #AbortoNao,1,NaN

In [26]:
for i in range(10):
  #printando na ordem - Replied tweet - tweet_original
  print(f'Tweet_1: {pair_replys_df.iloc[i]["tweet_1"]}')
  print(f'Tweet_2: {pair_replys_df.iloc[i]["tweet_2"]}')
  print()

Tweet_1: Bora subir, robozada?   #AbortoNao
Tweet_2: #AbortoNAO vida sim

Tweet_1: STF quer aplicar a medida enquanto a gente não tá vendo!! #AbortoNao
Tweet_2: Que Porra é essa ? #AbortoNao

Tweet_1: Enquanto lutamos pela nossa vida contra o covid19, o STF abre uma sessão pra liberar o aborto! Que país é esse?  #AbortoNao    #STFVergonhaNacional
Tweet_2: Assassinato nunca! #AbortoNAO

Tweet_1: STF quer aplicar a medida enquanto a gente não tá vendo!! #AbortoNao
Tweet_2: Vergonha desse STF  #AbortoNAO

Tweet_1: Bora subir, robozada?   #AbortoNao
Tweet_2: Gostaria de informar que devido a grande repercussão do vídeo de Araraquara, o jornalista foi demitido. Mas queremos mais, muito mais; queremos que o Ministério Público investigue todos os contratos feitos entre a prefeitura, as mídias, rádio e televisão de Araraquara #AbortoNAO

Tweet_1: É fácil defender o aborto sendo que você já nasceu. #AbortoNAO
Tweet_2: Há se as pessoas sobessem o mal que trszem para suas vidas, derrando sangue inocente, jamais defenderia tal ato. #AbortoNAO

Tweet_1: O que a Bíblia fala sobre o aborto?  "Antes que te formasse no ventre de sua mãe, Eu te conheci"  Jeremias 1.5 #AbortoNao
Tweet_2: Linda passagem da Bíblia. #AbortoNAO

Tweet_1: Bolsominions estão revoltados pq STF pode permitir aborto de fetos com zika vírus. Imagine q 1 mulher está grávida de um bebê q, se não nascer morto, viverá apenas meses. Pq obrigá-la a prosseguir com a gravidez q pode por a vida dela em risco? Ela é q tem q decidir! #AbortoSim
Tweet_2: É sobre as mulheres terem escolha. Se uma gestante com feto com zika vírus quiser seguir adiante com a gravidez, ela tem td o direito. Se ela quiser interromper a gravidez, ela deve ter td o direito tb. Simples! #AbortoSim

Tweet_1: O que a Bíblia fala sobre o aborto?  "Antes que te formasse no ventre de sua mãe, Eu te conheci"  Jeremias 1.5 #AbortoNao
Tweet_2: #AbortoNAO  Minha nossa! Isso não!

Tweet_1: Vamos subir #AbortoNao .  STF quer aprovar medida em plena pandemia.
Tweet_2: Com o STF não dá pra ter paz um segundo. #AbortoNAO #AbortoNao

In [27]:
#convertendo para csv
pair_replys_df.to_csv("Aborto_pares_reply.csv", index=False, encoding="utf-8")
files.download("Aborto_pares_reply.csv")

# **Pares Quote-Tweet**

In [28]:
#filtrando apenas quotes cujos tweets respondidos foram encontrados no dataset
quoteds = df.loc[(df["is_quote"] == True) & (df["quoted_text"].notna())]
quoteds

,tweet_id,user_id_original,text,created_at_original,retweet_count,like_count,is_retweet,retweeter_user_id,retweet_created_at,is_quote,quoted_tweet_id,quoted_user_id,quoted_text,is_reply,reply_to_tweet_id,reply_to_user_id,reply_to_screen_name,reply_text,class
9,1250556519118262272,4857849189,"Independente se você tem religião ou não, o tr...",Wed Apr 15 22:48:03 +0000 2020,2,2,True,8.591790e+17,Wed Apr 15 22:56:28 +0000 2020,True,1.250531e+18,1.087260e+09,STF quer aplicar a medida enquanto a gente não...,False,NaN,NaN,NaN,NaN,2
19,1250558648595763212,3711957436,eu peço para que você faça mais por crianças j...,Wed Apr 15 22:56:30 +0000 2020,0,0,False,NaN,NaN,True,1.250551e+18,8.696628e+17,"Eu peço a quem for a favor do aborto, para ref...",False,NaN,NaN,NaN,NaN,2
24,1250558653415002117,1204537219341529090,vc é um homem cis q se sua namorada engravidar...,Wed Apr 15 22:56:31 +0000 2020,0,0,False,NaN,NaN,True,1.250521e+18,1.721654e+08,"Toffoli, um lacaio da OMS, pautou ADI do abort...",False,NaN,NaN,NaN,NaN,2
28,1250553831672500236,1119256312062402560,Difícil demais viver nesse País! A que ponto c...,Wed Apr 15 22:37:22 +0000 2020,6,10,True,3.462951e+07,Wed Apr 15 22:56:33 +0000 2020,True,1.250546e+18,3.916062e+08,"Médico pedófilo, Fábio Duarte, estava preso p/...",False,NaN,NaN,NaN,NaN,2
29,1250558661052727297,718146038482223104,Primeiramente #foradoria segundamente nao somo...,Wed Apr 15 22:56:33 +0000 2020,0,0,False,NaN,NaN,True,1.250558e+18,3.025564e+08,#AbortoNao A hidroxicloroquina pode ter efeito...,False,NaN,NaN,NaN,NaN,2
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
15364,1250877969087823872,769252538872979456,vontade de virar do avesso lendo essas coisas ...,Thu Apr 16 20:05:22 +0000 2020,0,0,False,NaN,NaN,True,1.250569e+18,1.024455e+18,Aborto não é método contraceptivo!antes de esc...,False,NaN,NaN,NaN,NaN,2
15366,1250878008090677248,853330042767761408,Então não vamos melhorar o mundo sua burra do ...,Thu Apr 16 20:05:31 +0000 2020,0,0,False,NaN,NaN,True,1.250534e+18,1.116913e+18,"O aborto tem q ser permitido, pra evitar q cri...",False,NaN,NaN,NaN,NaN,2
15371,1250878154098397190,1036752804545810432,Faz juz...velho morre.... feto fica né? #Abo...,Thu Apr 16 20:06:06 +0000 2020,0,0,False,NaN,NaN,True,1.250872e+18,7.794370e+08,Palavras do Nelson Teich substituto de Mande...,False,NaN,NaN,NaN,NaN,2
15378,1250878960520572931,765543343581528064,é um direito sim! Mais vale abortar logo do qu...,Thu Apr 16 20:09:19 +0000 2020,0,0,False,NaN,NaN,True,1.250788e+18,6.054145e+08,Já que tenho útero posso opinar. Aborto é imor...,False,NaN,NaN,NaN,NaN,2
15379,1250878992175030278,709698858,Esses dois são judeus? Não sabia,Thu Apr 16 20:09:26 +0000 2020,0,0,False,NaN,NaN,True,1.250861e+18,1.725723e+08,S/ aborto e eventual voto de Fux e Barroso: a...,False,NaN,NaN,NaN,NaN,2

In [29]:
#Gerando pares (por quote)
pair_quote = [] #lista de dicionario que irá armazenar os pares
list_tweet_quote = quoteds["text"].tolist() #transformando tweets do df em lista de tweets
list_quote = quoteds["quoted_text"].tolist() #transformando quote do df em lista de quotes

for i in range(len(list_tweet_quote)):
  pair_quote.append({"tweet_1": list_quote[i], "tweet_2": list_tweet_quote[i] , "Class": 2, "Conflict": np.nan})

pair_quote_df = pd.DataFrame(pair_quote)
pair_quote_df

,tweet_1,tweet_2,Class,Conflict
0,STF quer aplicar a medida enquanto a gente não...,"Independente se você tem religião ou não, o tr...",2,NaN
1,"Eu peço a quem for a favor do aborto, para ref...",eu peço para que você faça mais por crianças j...,2,NaN
2,"Toffoli, um lacaio da OMS, pautou ADI do abort...",vc é um homem cis q se sua namorada engravidar...,2,NaN
3,"Médico pedófilo, Fábio Duarte, estava preso p/...",Difícil demais viver nesse País! A que ponto c...,2,NaN
4,#AbortoNao A hidroxicloroquina pode ter efeito...,Primeiramente #foradoria segundamente nao somo...,2,NaN
...,...,...,...,...
3023,Aborto não é método contraceptivo!antes de esc...,vontade de virar do avesso lendo essas coisas ...,2,NaN
3024,"O aborto tem q ser permitido, pra evitar q cri...",Então não vamos melhorar o mundo sua burra do ...,2,NaN
3025,Palavras do Nelson Teich substituto de Mande...,Faz juz...velho morre.... feto fica né? #Abo...,2,NaN
3026,Já que tenho útero posso opinar. Aborto é imor...,é um direito sim! Mais vale abortar logo do qu...,2,NaN
3027,S/ aborto e eventual voto de Fux e Barroso: a...,Esses dois são judeus? Não sabia,2,NaN

In [30]:
for i in range(10):
  #printando na ordem - Quoted tweet - tweet
  print(f'Tweet_1: {pair_quote_df.iloc[i]["tweet_1"]}')
  print(f'Tweet_2: {pair_quote_df.iloc[i]["tweet_2"]}')
  print()

Tweet_1: STF quer aplicar a medida enquanto a gente não tá vendo!! #AbortoNao
Tweet_2: Independente se você tem religião ou não, o três direitos básicos são: vida, propriedade privada e liberdade. Se você é um liberal ou um libertário deveria ter esses valores em mente. #AbortoNAO

Tweet_1: Eu peço a quem for a favor do aborto, para refletir se sua mãe tivesse feito essa opção quando estivesse grávida de você... Não é possível um ser humano agir com tamanha covardia!  #AbortoNao
Tweet_2: eu peço para que você faça mais por crianças já vivas e sofrendo de abandono e nas ruas, do que se preocupe com fetos que são simplesmente um amontoado de células

Tweet_1: Toffoli, um lacaio da OMS, pautou ADI do aborto durante o caos pandêmico.   O STF é uma VERGONHA! Só mesmo uma corte imoral e abjeta para concordar com essa sugestão criminosa da OMS, de assassinar inocentes para conter o víruschinês!  #AbortoNAO
Tweet_2: vc é um homem cis q se sua namorada engravidar vc vai largar entao fica caladinho pq sem utero sem opiniao importante cara

Tweet_1: Médico pedófilo, Fábio Duarte, estava preso p/filmar partes íntimas d crianças. Foi posto em liberdade hj. A juíza, na decisão, disse q segue orientação do CNJ (Conselho Nacional d Justiça), Presidido p/D Toffoli.  O pedófilo estava preso p/3ª vez, p/mesmo crime. Alerta Nacional.
Tweet_2: Difícil demais viver nesse País! A que ponto chegamos, meu Deus!  #AbortoNAO

Tweet_1: #AbortoNao A hidroxicloroquina pode ter efeitos colaterais (como qualquer medicamento). Já os efeitos irreversíveis do aborto são certos.
Tweet_2: Primeiramente #foradoria segundamente nao somos bobos, chega de usar nosso dinheiro #SenadoPL149NÃO terceiramente qual o sentido de colocar aborto pra votar agora, se todos estao lutando pra viver?! #AbortoNAO  Muito trabalho pra gnt robozada

Tweet_1: não acredito que ainda tenho que ficar lendo essas coisas...  será que nunca as mulheres vão ser respeitadas como merecem???? #AbortoSIM
Tweet_2: O pior é ver mulheres defendendo esse tipo de ideia. Outro dia discuti com a sobrinha do meu cunhado que diz que quem é a favor do aborto é vagabunda e ainda a guria defende a pena de morte.

Tweet_1: Eu sou contra o aborto, o feto n tem nd a ver com a suas atitudes. Ele n tem como se defender."A, mas e se a mulher for estuprada e engravidar" GENTE A CRIANÇA NÃO TEM CULPA, nesse caso quem tem culpa é o estuprador, então tem q resolver os problemas em relação a ele! #AbortoNAO
Tweet_2: quem aborta tem que morrer junto

Tweet_1: Bora subir, robozada?   #AbortoNao
Tweet_2: Difícil acreditar nesse corona virus, ele somente pega em os envolvidos no golpe e pessoas que exploram a existência do virus, do resto nada, somente infectados sem nome e mortos sem corpos exceção daqueles que morreram e usaram como se fosse do corona. ou seja (virus xili-ling)

Tweet_1: Antes um feto abortado do que mais uma criança morando nas ruas ou então nos indices de criminalidade. #AbortoSim
Tweet_2: eu sigo as pessoas certas

Tweet_1: Vamos começar a pressão ao STF já.  #AbortoNAO
Tweet_2: #AbortoNão Estão aproveitando a história do virus para impor questões que os brasileiros não aceitam

In [31]:
#convertendo para csv
pair_quote_df.to_csv("Aborto_pares_quote.csv", index=False, encoding="utf-8")
files.download("Aborto_pares_quote.csv")

In [32]:
#concatenando os datasets parciais:
df_aborto = pd.concat([pair_generics_df, pair_replys_df, pair_quote_df], ignore_index=True, axis = 0)
df_aborto

,tweet_1,tweet_2,Class,Conflict
0,"""Fiquem em casa para não morrer de corona víru...",Proteção para os indefesos. Não à cultura de m...,0,NaN
1,"Sou a favor de liberar o aborto, somente o dia...","#AbortoNAO STF SÓ TEM BANDIDO, SAFADOS, CANALH...",0,NaN
2,"#AbortoNao/ ai a criança nasce sendo odiada, s...","tá bom pró-vidas, agora me expliquem a lógica:...",0,NaN
3,Quem foi o eleitor do bozonaro Que criou as t...,"#AbortoSim um caralho, você mulher é dona sim ...",0,NaN
4,"se não é seu corpo, não é você quem decide. #A...","Uma mulher abortista, poderia ter sido abortad...",0,NaN
...,...,...,...,...
14752,Aborto não é método contraceptivo!antes de esc...,vontade de virar do avesso lendo essas coisas ...,2,NaN
14753,"O aborto tem q ser permitido, pra evitar q cri...",Então não vamos melhorar o mundo sua burra do ...,2,NaN
14754,Palavras do Nelson Teich substituto de Mande...,Faz juz...velho morre.... feto fica né? #Abo...,2,NaN
14755,Já que tenho útero posso opinar. Aborto é imor...,é um direito sim! Mais vale abortar logo do qu...,2,NaN
14756,S/ aborto e eventual voto de Fux e Barroso: a...,Esses dois são judeus? Não sabia,2,NaN

In [33]:
#convertendo para csv
df_aborto.to_csv("Aborto_pares.csv", index=False, encoding="utf-8")
files.download("Aborto_pares.csv")