# **Projeto de Graduação em Computação II [2026-Q1]**

Universidade Federal do ABC

Orientador Carlos da Silva dos Santos

### **EQUIPE**

---

Caio Cardoso Dos Santos - RA: 11202021632

Victor Ravazio de Lima - RA: 11201920941

### **IMPLEMENTAÇÃO**
---

In [99]:
# modulo para importar dataset a partir de um link
!pip install gdown

Requirement already satisfied: gdown in /usr/local/lib/python3.12/dist-packages (5.2.2)
Requirement already satisfied: beautifulsoup4 in /usr/local/lib/python3.12/dist-packages (from gdown) (4.13.5)
Requirement already satisfied: filelock in /usr/local/lib/python3.12/dist-packages (from gdown) (3.29.0)
Requirement already satisfied: requests[socks] in /usr/local/lib/python3.12/dist-packages (from gdown) (2.32.4)
Requirement already satisfied: tqdm in /usr/local/lib/python3.12/dist-packages (from gdown) (4.67.3)
Requirement already satisfied: soupsieve>1.2 in /usr/local/lib/python3.12/dist-packages (from beautifulsoup4->gdown) (2.8.3)
Requirement already satisfied: typing-extensions>=4.0.0 in /usr/local/lib/python3.12/dist-packages (from beautifulsoup4->gdown) (4.15.0)
Requirement already satisfied: charset_normalizer<4,>=2 in /usr/local/lib/python3.12/dist-packages (from requests[socks]->gdown) (3.4.7)
Requirement already satisfied: idna<4,>=2.5 in /usr/local/lib/python3.12/dist-packages (from requests[socks]->gdown) (3.13)
Requirement already satisfied: urllib3<3,>=1.21.1 in /usr/local/lib/python3.12/dist-packages (from requests[socks]->gdown) (2.5.0)
Requirement already satisfied: certifi>=2017.4.17 in /usr/local/lib/python3.12/dist-packages (from requests[socks]->gdown) (2026.4.22)
Requirement already satisfied: PySocks!=1.5.7,>=1.5.6 in /usr/local/lib/python3.12/dist-packages (from requests[socks]->gdown) (1.7.1)

In [100]:
# Módulo para extrair entidades
!pip install spacy
!python -m spacy download pt_core_news_sm

Requirement already satisfied: spacy in /usr/local/lib/python3.12/dist-packages (3.8.14)
Requirement already satisfied: spacy-legacy<3.1.0,>=3.0.11 in /usr/local/lib/python3.12/dist-packages (from spacy) (3.0.12)
Requirement already satisfied: spacy-loggers<2.0.0,>=1.0.0 in /usr/local/lib/python3.12/dist-packages (from spacy) (1.0.5)
Requirement already satisfied: murmurhash<1.1.0,>=0.28.0 in /usr/local/lib/python3.12/dist-packages (from spacy) (1.0.15)
Requirement already satisfied: cymem<2.1.0,>=2.0.2 in /usr/local/lib/python3.12/dist-packages (from spacy) (2.0.13)
Requirement already satisfied: preshed<3.1.0,>=3.0.2 in /usr/local/lib/python3.12/dist-packages (from spacy) (3.0.13)
Requirement already satisfied: thinc<8.4.0,>=8.3.12 in /usr/local/lib/python3.12/dist-packages (from spacy) (8.3.13)
Requirement already satisfied: wasabi<1.2.0,>=0.9.1 in /usr/local/lib/python3.12/dist-packages (from spacy) (1.1.3)
Requirement already satisfied: srsly<3.0.0,>=2.5.3 in /usr/local/lib/python3.12/dist-packages (from spacy) (2.5.3)
Requirement already satisfied: catalogue<2.1.0,>=2.0.6 in /usr/local/lib/python3.12/dist-packages (from spacy) (2.0.10)
Requirement already satisfied: weasel<2.0.0,>=1.0.0 in /usr/local/lib/python3.12/dist-packages (from spacy) (1.0.0)
Requirement already satisfied: confection<2.0.0,>=1.3.2 in /usr/local/lib/python3.12/dist-packages (from spacy) (1.3.3)
Requirement already satisfied: typer<1.0.0,>=0.3.0 in /usr/local/lib/python3.12/dist-packages (from spacy) (0.24.2)
Requirement already satisfied: tqdm<5.0.0,>=4.38.0 in /usr/local/lib/python3.12/dist-packages (from spacy) (4.67.3)
Requirement already satisfied: numpy>=1.19.0 in /usr/local/lib/python3.12/dist-packages (from spacy) (2.0.2)
Requirement already satisfied: requests<3.0.0,>=2.13.0 in /usr/local/lib/python3.12/dist-packages (from spacy) (2.32.4)
Requirement already satisfied: pydantic<3.0.0,>=2.0.0 in /usr/local/lib/python3.12/dist-packages (from spacy) (2.12.3)
Requirement already satisfied: jinja2 in /usr/local/lib/python3.12/dist-packages (from spacy) (3.1.6)
Requirement already satisfied: setuptools in /usr/local/lib/python3.12/dist-packages (from spacy) (75.2.0)
Requirement already satisfied: packaging>=20.0 in /usr/local/lib/python3.12/dist-packages (from spacy) (26.1)
Requirement already satisfied: annotated-types>=0.6.0 in /usr/local/lib/python3.12/dist-packages (from pydantic<3.0.0,>=2.0.0->spacy) (0.7.0)
Requirement already satisfied: pydantic-core==2.41.4 in /usr/local/lib/python3.12/dist-packages (from pydantic<3.0.0,>=2.0.0->spacy) (2.41.4)
Requirement already satisfied: typing-extensions>=4.14.1 in /usr/local/lib/python3.12/dist-packages (from pydantic<3.0.0,>=2.0.0->spacy) (4.15.0)
Requirement already satisfied: typing-inspection>=0.4.2 in /usr/local/lib/python3.12/dist-packages (from pydantic<3.0.0,>=2.0.0->spacy) (0.4.2)
Requirement already satisfied: charset_normalizer<4,>=2 in /usr/local/lib/python3.12/dist-packages (from requests<3.0.0,>=2.13.0->spacy) (3.4.7)
Requirement already satisfied: idna<4,>=2.5 in /usr/local/lib/python3.12/dist-packages (from requests<3.0.0,>=2.13.0->spacy) (3.13)
Requirement already satisfied: urllib3<3,>=1.21.1 in /usr/local/lib/python3.12/dist-packages (from requests<3.0.0,>=2.13.0->spacy) (2.5.0)
Requirement already satisfied: certifi>=2017.4.17 in /usr/local/lib/python3.12/dist-packages (from requests<3.0.0,>=2.13.0->spacy) (2026.4.22)
Requirement already satisfied: blis<1.4.0,>=1.3.0 in /usr/local/lib/python3.12/dist-packages (from thinc<8.4.0,>=8.3.12->spacy) (1.3.3)
Requirement already satisfied: click>=8.2.1 in /usr/local/lib/python3.12/dist-packages (from typer<1.0.0,>=0.3.0->spacy) (8.3.3)
Requirement already satisfied: shellingham>=1.3.0 in /usr/local/lib/python3.12/dist-packages (from typer<1.0.0,>=0.3.0->spacy) (1.5.4)
Requirement already satisfied: rich>=12.3.0 in /usr/local/lib/python3.12/dist-packages (from typer<1.0.0,>=0.3.0->spacy) (13.9.4)
Requirement already satisfied: annotated-doc>=0.0.2 in /usr/local/lib/python3.12/dist-packages (from typer<1.0.0,>=0.3.0->spacy) (0.0.4)
Requirement already satisfied: cloudpathlib>=0.7.0 in /usr/local/lib/python3.12/dist-packages (from weasel<2.0.0,>=1.0.0->spacy) (0.23.0)
Requirement already satisfied: smart-open>=5.2.1 in /usr/local/lib/python3.12/dist-packages (from weasel<2.0.0,>=1.0.0->spacy) (7.6.0)
Requirement already satisfied: httpx>=0.24.0 in /usr/local/lib/python3.12/dist-packages (from weasel<2.0.0,>=1.0.0->spacy) (0.28.1)
Requirement already satisfied: MarkupSafe>=2.0 in /usr/local/lib/python3.12/dist-packages (from jinja2->spacy) (3.0.3)
Requirement already satisfied: anyio in /usr/local/lib/python3.12/dist-packages (from httpx>=0.24.0->weasel<2.0.0,>=1.0.0->spacy) (4.13.0)
Requirement already satisfied: httpcore==1.* in /usr/local/lib/python3.12/dist-packages (from httpx>=0.24.0->weasel<2.0.0,>=1.0.0->spacy) (1.0.9)
Requirement already satisfied: h11>=0.16 in /usr/local/lib/python3.12/dist-packages (from httpcore==1.*->httpx>=0.24.0->weasel<2.0.0,>=1.0.0->spacy) (0.16.0)
Requirement already satisfied: markdown-it-py>=2.2.0 in /usr/local/lib/python3.12/dist-packages (from rich>=12.3.0->typer<1.0.0,>=0.3.0->spacy) (4.0.0)
Requirement already satisfied: pygments<3.0.0,>=2.13.0 in /usr/local/lib/python3.12/dist-packages (from rich>=12.3.0->typer<1.0.0,>=0.3.0->spacy) (2.20.0)
Requirement already satisfied: wrapt in /usr/local/lib/python3.12/dist-packages (from smart-open>=5.2.1->weasel<2.0.0,>=1.0.0->spacy) (2.1.2)
Requirement already satisfied: mdurl~=0.1 in /usr/local/lib/python3.12/dist-packages (from markdown-it-py>=2.2.0->rich>=12.3.0->typer<1.0.0,>=0.3.0->spacy) (0.1.2)
Collecting pt-core-news-sm==3.8.0
  Downloading https://github.com/explosion/spacy-models/releases/download/pt_core_news_sm-3.8.0/pt_core_news_sm-3.8.0-py3-none-any.whl (13.0 MB)
     ━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━ 13.0/13.0 MB 59.1 MB/s eta 0:00:00
✔ Download and installation successful
You can now load the package via spacy.load('pt_core_news_sm')
⚠ Restart to reload dependencies
If you are in a Jupyter or Colab notebook, you may need to restart Python in
order to load all the package's dependencies. You can do this by selecting the
'Restart kernel' or 'Restart runtime' option.

In [101]:
#Bibliotecas
import pandas as pd
import numpy as np
from google.colab import files
import gdown
import matplotlib.pyplot as plt
import random

In [102]:
# baixando dataset para o collab
import gdown

file_id = "11PoBbVSQXAFHWgXp36pC0Gc7ZzUBgRLc"
url = f"https://drive.google.com/uc?id={file_id}"

gdown.download(url, "cloroquina.csv", quiet=False)

Downloading...
From: https://drive.google.com/uc?id=11PoBbVSQXAFHWgXp36pC0Gc7ZzUBgRLc
To: /content/cloroquina.csv
100%|██████████| 21.6M/21.6M [00:00<00:00, 31.1MB/s]

'cloroquina.csv'

In [103]:
#carregando o dataset
df = pd.read_csv ("cloroquina.csv")
df.head()

,tweet_id,user_id_original,text,created_at_original,retweet_count,like_count,is_retweet,retweeter_user_id,retweet_created_at,is_quote,quoted_tweet_id,quoted_user_id,quoted_text,is_reply,reply_to_tweet_id,reply_to_user_id,reply_to_screen_name,reply_text,class
0,1263053750681382912,74756085,Sem distorções. JB brinca: tubaína ou cloroquina,Wed May 20 10:27:35 +0000 2020,2464,11709,True,1.163629e+18,Wed May 20 17:48:15 +0000 2020,False,NaN,NaN,NaN,False,NaN,NaN,NaN,NaN,0
1,1263164652806078466,64559578,Está se tornando uma irresponsabilidade a manu...,Wed May 20 17:48:16 +0000 2020,0,0,False,NaN,NaN,False,NaN,NaN,NaN,False,NaN,NaN,NaN,NaN,0
2,1263131993895841793,1087259768,Agora é oficial!!! Vamos de novo: Melhor ter u...,Wed May 20 15:38:29 +0000 2020,934,2934,True,1.254218e+18,Wed May 20 17:48:16 +0000 2020,True,1.263130e+18,128372940.0,O divulga orientações para tratamento da Covi...,False,NaN,NaN,NaN,NaN,2
3,1263161628620701696,1262972424880041985,O publicou nesta manhã o novo protocolo do co...,Wed May 20 17:36:15 +0000 2020,22,61,True,2.616611e+07,Wed May 20 17:48:16 +0000 2020,False,NaN,NaN,NaN,False,NaN,NaN,NaN,NaN,0
4,1263154938672267267,1138847289978626049,O UOL fez uma matéria sobre o protocolo para c...,Wed May 20 17:09:40 +0000 2020,276,1196,True,1.256312e+18,Wed May 20 17:48:17 +0000 2020,False,NaN,NaN,NaN,False,NaN,NaN,NaN,NaN,0

In [104]:
#numero total de instancias no dataset
df.shape

(67085, 19)

In [105]:
#numero de tweets genericos (não é quote nem reply)
generics = df.loc[(df["is_quote"] == False) & (df["is_reply"] == False)]
generics.shape[0]

16360

In [106]:
#numero de tweets replys totais (com e sem respostas os respectivos tweets originais obtidos)
replys_tot = df.loc[df["is_reply"] == True]
replys_tot.shape[0]

22800

In [107]:
#numero de tweets replys com respostas encontradas
replys = df.loc[(df["is_reply"]) & (df["reply_text"].notna())]
replys.shape[0]

7057

In [108]:
#numero de quotes
quoteds = df.loc[df["is_quote"] == True]
quoteds.shape[0]

28211

In [109]:
#intersecções entre quotes e replys
replys_quotes = df.loc[(df["is_reply"] == True) & (df["is_quote"] == True)]
replys_quotes.shape[0]

286

In [110]:
tot = generics.shape[0] + replys_tot.shape[0] + quoteds.shape[0] - replys_quotes.shape[0]
tot

67085

In [111]:
replys_tot.head()

,tweet_id,user_id_original,text,created_at_original,retweet_count,like_count,is_retweet,retweeter_user_id,retweet_created_at,is_quote,quoted_tweet_id,quoted_user_id,quoted_text,is_reply,reply_to_tweet_id,reply_to_user_id,reply_to_screen_name,reply_text,class
5,1263164657243693056,1227315878376726529,Mas e daí? Eu sou Messias mas não faço milagre...,Wed May 20 17:48:17 +0000 2020,0,0,False,NaN,NaN,False,NaN,NaN,NaN,True,1.263155e+18,1.257497e+18,pedrofeospa,NaN,1
6,1263164658132844546,986754770,Vc q usa tanto tempo teve algum problema? Se f...,Wed May 20 17:48:17 +0000 2020,0,0,False,NaN,NaN,False,NaN,NaN,NaN,True,1.263111e+18,1.162330e+18,MrciaAmaralLuc2,Tomo cloroquina há 16 anos. A dosagem é super-...,1
11,1263164667372941313,1254084510934806530,"Olha, o criminoso do ABC toma atitude semelhan...",Wed May 20 17:48:19 +0000 2020,0,0,False,NaN,NaN,False,NaN,NaN,NaN,True,1.263163e+18,1.459470e+07,UOLNoticias,NaN,1
15,1263164671223267330,82598300,Muita Cloroquina na mente...,Wed May 20 17:48:20 +0000 2020,0,0,False,NaN,NaN,False,NaN,NaN,NaN,True,1.263164e+18,1.260714e+18,AdelioPastor,NaN,1
17,1263164672733319171,1253842436239118336,é surreal que nossos tribunais permitam o uso ...,Wed May 20 17:48:21 +0000 2020,0,0,False,NaN,NaN,False,NaN,NaN,NaN,True,1.263066e+18,1.283729e+08,jairbolsonaro,NaN,1

# **Pares Tweets genéricos**

In [112]:
generics = df.loc[(df["is_quote"] == False) & (df["is_reply"] == False)]
generics

,tweet_id,user_id_original,text,created_at_original,retweet_count,like_count,is_retweet,retweeter_user_id,retweet_created_at,is_quote,quoted_tweet_id,quoted_user_id,quoted_text,is_reply,reply_to_tweet_id,reply_to_user_id,reply_to_screen_name,reply_text,class
0,1263053750681382912,74756085,Sem distorções. JB brinca: tubaína ou cloroquina,Wed May 20 10:27:35 +0000 2020,2464,11709,True,1.163629e+18,Wed May 20 17:48:15 +0000 2020,False,NaN,NaN,NaN,False,NaN,NaN,NaN,NaN,0
1,1263164652806078466,64559578,Está se tornando uma irresponsabilidade a manu...,Wed May 20 17:48:16 +0000 2020,0,0,False,NaN,NaN,False,NaN,NaN,NaN,False,NaN,NaN,NaN,NaN,0
3,1263161628620701696,1262972424880041985,O publicou nesta manhã o novo protocolo do co...,Wed May 20 17:36:15 +0000 2020,22,61,True,2.616611e+07,Wed May 20 17:48:16 +0000 2020,False,NaN,NaN,NaN,False,NaN,NaN,NaN,NaN,0
4,1263154938672267267,1138847289978626049,O UOL fez uma matéria sobre o protocolo para c...,Wed May 20 17:09:40 +0000 2020,276,1196,True,1.256312e+18,Wed May 20 17:48:17 +0000 2020,False,NaN,NaN,NaN,False,NaN,NaN,NaN,NaN,0
7,1263108325262217221,27703690,Bolsonaro finalmente conseguiu forçar o Min. d...,Wed May 20 14:04:26 +0000 2020,1378,7764,True,1.134326e+18,Wed May 20 17:48:18 +0000 2020,False,NaN,NaN,NaN,False,NaN,NaN,NaN,NaN,0
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
67067,1263565913082732546,19593634,General que comanda Ministério da Saúde ordena...,Thu May 21 20:22:44 +0000 2020,0,0,False,NaN,NaN,False,NaN,NaN,NaN,False,NaN,NaN,NaN,NaN,0
67068,1263565925011292160,1258090859351945216,"Pra direita cloroquina, pra esquerda tubaína, ...",Thu May 21 20:22:47 +0000 2020,0,0,False,NaN,NaN,False,NaN,NaN,NaN,False,NaN,NaN,NaN,NaN,0
67071,1263565934498848769,1251907601027289095,#ministériodaSaúde cloroquina fosse bom você n...,Thu May 21 20:22:49 +0000 2020,0,0,False,NaN,NaN,False,NaN,NaN,NaN,False,NaN,NaN,NaN,NaN,0
67074,1263565959941537795,1014862374422089729,Cloroquina é tão eficiente que vc tem q assina...,Thu May 21 20:22:55 +0000 2020,0,0,False,NaN,NaN,False,NaN,NaN,NaN,False,NaN,NaN,NaN,NaN,0
67084,1263120648274132992,2923397967,"“Redução dos glóbulos brancos, disfunção do fí...",Wed May 20 14:53:24 +0000 2020,270,1307,False,NaN,NaN,False,NaN,NaN,NaN,False,NaN,NaN,NaN,NaN,0

In [113]:
#gerando pares de tweets generico - Por amostra
sample_size = 10000
pair_generics = [] #lista de dicionario correspondente aos pares
list_tweet_generics = generics["text"].tolist() #transformando tweets em lista

for i in range(sample_size):
  pair_gen = random.sample(list_tweet_generics, 2)
  pair_generics.append({"tweet_1": pair_gen[0], "tweet_2": pair_gen[1], "Class": 0, "Conflict": np.nan})

pair_generics_df = pd.DataFrame(pair_generics) #transformando a lista de dicionarios em df
pair_generics_df

,tweet_1,tweet_2,Class,Conflict
0,(Hidroxi)Cloroquina: quem precisar e avaliar (...,Não existe comprovação científica sobre a efic...,0,NaN
1,"E ssa gente querendo cancelar o Lula, só pq el...","acaba de dizer em rede nacional que a Aspen, u...",0,NaN
2,Se a mídia está contra a Cloroquina é porque é...,Tinha que jogar cloroquina nos reservatórios d...,0,NaN
3,Bora dropar cloroquina pra ficar doidão,Assim como o ateu deixa de ser ateu quando pre...,0,NaN
4,CORONAVÍRUS: Ministério da Saúde orienta uso d...,KKKKK CHEIRADOR D PO FALANDO Q USARIA CLOROQUI...,0,NaN
...,...,...,...,...
9995,Mandetta: quem são os médicos que queriam alte...,Pesquisadores divulgam documento contra a libe...,0,NaN
9996,é uma a facção. a facção dos NÉSCIOS.,Caraí de cloroquina. Se é pra usar droga que n...,0,NaN
9997,"Eu não estou entendo uma coisa, a cloroquina e...","Se não fosse o maior dano no país, que provave...",0,NaN
9998,"Bem, pessoal, as primeiras reportagens sobre a...",tô com a música da cloroquina na cabeça,0,NaN
9999,Quer dizer então que a cloroquina só funciona ...,"agora tão defendendo cloroquina e falando ""pró...",0,NaN

In [114]:
#exibindo uma pequena amostra

for i in range(10):
  #printando na ordem - Replied tweet - tweet_original
  print(f'Tweet_1: {pair_generics_df.iloc[i]["tweet_1"]}')
  print(f'Tweet_2: {pair_generics_df.iloc[i]["tweet_2"]}')
  print()

Tweet_1: (Hidroxi)Cloroquina: quem precisar e avaliar (junto ao médico) que vale, usa, quem não quiser, não usa. Simples assim.
Tweet_2: Não existe comprovação científica sobre a eficácia da cloroquina contra a Covid-19! Não compre essa ideia! Enquanto milhares de pessoas morrem no Brasil, vítimas do novo coronavírus, o presidente faz piada e brinca de dança das cadeiras nos ministérios. Não se engane! #covid19

Tweet_1: E ssa gente querendo cancelar o Lula, só pq ele se expressou mal? É sério que vcs tão querendo comparar, um dos maiores líderes politicos da América Latina, que revolucionou a vida de milhões de brasileiroxs,  com o assassino e torturador atual presidente da cloroquina do Brasil?
Tweet_2: acaba de dizer em rede nacional que a Aspen, uma indústria farmacêutica é a fabricante da Cloroquina, sendo seu principal representante apoiador e financiador de . Entendeu agora a tara pelo Cloroquina direita?

Tweet_1: Se a mídia está contra a Cloroquina é porque é boa no combate ao vírus ...
Tweet_2: Tinha que jogar cloroquina nos reservatórios de água

Tweet_1: Bora dropar cloroquina pra ficar doidão
Tweet_2: Assim como o ateu deixa de ser ateu quando precisa de Deus,a esquerda é quando precisa da cloroquina .kkk

Tweet_1: CORONAVÍRUS: Ministério da Saúde orienta uso da Cloroquina e Azitromicina para tratamento de pacientes com a Covid-19 no Brasil -  via
Tweet_2: KKKKK CHEIRADOR D PO FALANDO Q USARIA CLOROQUINA CALA TUA BOCA SEU NOIA

Tweet_1: GENTE, OLHEM QUE BOAS NOTÍCIAS!! A soja pode salvar a economia brasileira! Que o povo dance nas ruas!   #Cloroquina na Saúde e #soja na Economia! Votei!!  #SojaBrasileira #agronegocio #Economia  #EduardoBolsonaroTemRazao #VirusChines #China #CloroquinaCura
Tweet_2: Não trate como Tubaína quem te trata como Cloroquina.

Tweet_1: Segundo fight com o papai por causa da CLOROQUINA, acabei me excedendo de dizendo que eu queria que o Bolsonaro rei do gado tome no cu. Que meu pai não estudou pra ser médico, que sim, ele estava sendo ignorante, falei que a família Bolsonaro tinha que ser presa, parte de milicia
Tweet_2: As novas orientações para tratamento da Covid-19, divulgadas nesta quarta-feira pelo Ministério da Saúde, divergem de TODOS os protocolos já elaborados pela pasta. Explico nesta matéria e neste fio:

Tweet_1: Mas já??? Acabou de liberar  a cloroquina hj e a esquerda e a turma do contra  já  encontraram um cadáver  pra servir de palanque.  Coitado  do deputado do psl... Nem morrer com dignidade  pode.
Tweet_2: Lula, num ato falho,diz "ainda bem" pra COVID.  Bozo disse:"E daí?Sou messias,mas não faço milagre" "Quem é de direita toma cloroquina,quem é de esquerda toma tubaina" E riu.  Fala de um não mata ninguém, fala de outro tem feito pessoas sair as ruas pra morrer.  Sem comparação.

Tweet_1: Olha o absurdo da ... A reportagem dá ênfase as "desculpas" desse bandido, , amenizando a MONSTRUOSIDADE que ele falou, logo depois coloca a fala do presidente  sobre a cloroquina na intenção de equiparar ao que o bandido falou... Vergonha! #CNNLixo
Tweet_2: A vontade é mandar essas veia tudo enfiar a Cloroquina no cu

Tweet_1: Bolsonaro quis mudar a bula da cloroquina p satisfazer seu ego nojento. Mas era ele mesmo q dizia em campanha que "eu n entendo nada, quem entende são os meus ministros" e agora ele até médico/cientista/pesquisador é. Não era de ditadura que a direita tava correndo?! Pois bem...
Tweet_2: Olha só! Assinatura do paciente: último desejo de um condenado...até à morte!   Após pressão de Bolsonaro, cloroquina é liberada para todos os pacientes com Covid-19

In [115]:
#convertendo para csv
pair_generics_df.to_csv("Cloroquina_pares_genericos.csv", index=False, encoding="utf-8")
files.download("Cloroquina_pares_genericos.csv")

# **Pares Tweet-Reply**

In [116]:
#filtrando apenas replys cujos tweets respondidos foram encontrados no dataset
replys = df.loc[(df["is_reply"] == True) & (df["reply_text"].notna())]
replys

,tweet_id,user_id_original,text,created_at_original,retweet_count,like_count,is_retweet,retweeter_user_id,retweet_created_at,is_quote,quoted_tweet_id,quoted_user_id,quoted_text,is_reply,reply_to_tweet_id,reply_to_user_id,reply_to_screen_name,reply_text,class
6,1263164658132844546,986754770,Vc q usa tanto tempo teve algum problema? Se f...,Wed May 20 17:48:17 +0000 2020,0,0,False,NaN,NaN,False,NaN,NaN,NaN,True,1.263111e+18,1.162330e+18,MrciaAmaralLuc2,Tomo cloroquina há 16 anos. A dosagem é super-...,1
29,1263130475167657984,128372940,"- Ainda não existe comprovação científica, mas...",Wed May 20 15:32:27 +0000 2020,2799,15168,True,1.168434e+18,Wed May 20 17:48:24 +0000 2020,False,NaN,NaN,NaN,True,1.263130e+18,1.283729e+08,jairbolsonaro,O divulga orientações para tratamento da Covi...,1
43,1263164703548887040,735514234877054976,Nunca precisei assinar um documento depois de ...,Wed May 20 17:48:28 +0000 2020,0,0,False,NaN,NaN,False,NaN,NaN,NaN,True,1.263130e+18,1.283729e+08,jairbolsonaro,O divulga orientações para tratamento da Covi...,1
57,1263164742291652609,404834547,"""2. A Cloroquina e a hidroxicloroquina podem c...",Wed May 20 17:48:37 +0000 2020,0,0,False,NaN,NaN,False,NaN,NaN,NaN,True,1.263165e+18,4.048345e+08,ViiPassos,"Trecho do termo de consentimento: ""não há, at...",1
68,1263164761384067075,1115704338117038081,Pq as pessoas acham que só os médicos entendem...,Wed May 20 17:48:42 +0000 2020,0,0,False,NaN,NaN,False,NaN,NaN,NaN,True,1.263158e+18,4.054589e+07,AndreiaSadi,Do no : “sabe qual minha opiniao sobre a clo...,1
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
67042,1263565780333080578,70144603,"Mais cloroquina, menos covas. Quem deve decidi...",Thu May 21 20:22:12 +0000 2020,0,0,False,NaN,NaN,False,NaN,NaN,NaN,True,1.263530e+18,4.009595e+07,SenadoFederal,Senadores questionam liberação de uso da cloro...,1
67052,1263565834745757700,42743924,"Espero que vc não precise, e se precisar use.....",Thu May 21 20:22:25 +0000 2020,0,0,False,NaN,NaN,False,NaN,NaN,NaN,True,1.263188e+18,1.391834e+08,andrizek,E daí?,1
67070,1263565931013423107,716607014290456577,"Cloroquina não fica doido por isto é ilegal, n...",Thu May 21 20:22:48 +0000 2020,0,0,False,NaN,NaN,False,NaN,NaN,NaN,True,1.263566e+18,1.183370e+18,sou_eumesma,"Cloroquina não!!Mas maconha,crack,cocaína...""e...",1
67076,1263565967587713027,1046914293462159360,EU QUERO YER O DIREITO DE TOMAR CLOROQUINA! A ...,Thu May 21 20:22:57 +0000 2020,0,0,False,NaN,NaN,False,NaN,NaN,NaN,True,1.263203e+18,1.388402e+09,RenovaMidia,"""Nós não faremos a distribuição e nem aplicaçã...",1
67080,1263565981164716056,3105395998,"Entendo seu ponto, já li inúmeros estudos e pu...",Thu May 21 20:23:00 +0000 2020,0,0,False,NaN,NaN,False,NaN,NaN,NaN,True,1.263542e+18,1.235277e+08,jaurojr,"Cara, deixa eu te explicar: não existem estudo...",1

In [117]:
#Gerando pares (por reply)
pair_replys = [] #lista de dicionario que irá armazenar os pares
list_tweet_replys = replys["text"].tolist() #transformando tweets do df em lista de tweets
list_replys = replys["reply_text"].tolist() #transformando replys do df em lista de replys

for i in range(len(list_tweet_replys)):
  pair_replys.append({"tweet_1":  list_replys[i], "tweet_2": list_tweet_replys[i], "Class": 1, "Conflict": np.nan})

pair_replys_df = pd.DataFrame(pair_replys)
pair_replys_df

,tweet_1,tweet_2,Class,Conflict
0,Tomo cloroquina há 16 anos. A dosagem é super-...,Vc q usa tanto tempo teve algum problema? Se f...,1,NaN
1,O divulga orientações para tratamento da Covi...,"- Ainda não existe comprovação científica, mas...",1,NaN
2,O divulga orientações para tratamento da Covi...,Nunca precisei assinar um documento depois de ...,1,NaN
3,"Trecho do termo de consentimento: ""não há, at...","""2. A Cloroquina e a hidroxicloroquina podem c...",1,NaN
4,Do no : “sabe qual minha opiniao sobre a clo...,Pq as pessoas acham que só os médicos entendem...,1,NaN
...,...,...,...,...
7052,Senadores questionam liberação de uso da cloro...,"Mais cloroquina, menos covas. Quem deve decidi...",1,NaN
7053,E daí?,"Espero que vc não precise, e se precisar use.....",1,NaN
7054,"Cloroquina não!!Mas maconha,crack,cocaína...""e...","Cloroquina não fica doido por isto é ilegal, n...",1,NaN
7055,"""Nós não faremos a distribuição e nem aplicaçã...",EU QUERO YER O DIREITO DE TOMAR CLOROQUINA! A ...,1,NaN
7056,"Cara, deixa eu te explicar: não existem estudo...","Entendo seu ponto, já li inúmeros estudos e pu...",1,NaN

In [118]:
for i in range(10):
  #printando na ordem - Replied tweet - tweet_original
  print(f'Tweet_1: {pair_replys_df.iloc[i]["tweet_1"]}')
  print(f'Tweet_2: {pair_replys_df.iloc[i]["tweet_2"]}')
  print()

Tweet_1: Tomo cloroquina há 16 anos. A dosagem é super- controlada através de exames periódicos. O uso excessivo pode danificar rins, fígado, pâncreas além da questão cardíaca! Esse irresponsável que que a população se exploda!!!
Tweet_2: Vc q usa tanto tempo teve algum problema? Se fosse esse perigo todo duvido que usaria por tanto tempo.  Ngm vai usar Cloroquina ou HCL por 16 anos sua maluca, é um tratamento de 7 dias com dose controla que o médico irá receitar.

Tweet_1: O  divulga orientações para tratamento da Covid-19, onde a Cloroquina pode ser ministrada em casos leves, com recomendação médica e autorização do próprio paciente/família.
Tweet_2: - Ainda não existe comprovação científica, mas sendo monitorada e usada no Brasil e no mundo. Contudo, estamos em Guerra: “Pior do que ser derrotado é a vergonha de não ter lutado.”  - Deus abençoe o nosso Brasil.

Tweet_1: O  divulga orientações para tratamento da Covid-19, onde a Cloroquina pode ser ministrada em casos leves, com recomendação médica e autorização do próprio paciente/família.
Tweet_2: Nunca precisei assinar um documento depois de um médico me receitar qualquer medicamento, não parece estranho a vocês que devamos fazer isto com a cloroquina? Quer dizer, vamos tirar a responsabilidade do Presidente Jair Bolsonaro que tanto faz questão desse medicamento para nós?

Tweet_1: Trecho do termo de consentimento:  "não há, até o momento, estudos suficientes para garantir certeza de melhora clínica dos pacientes com COVID-19 quando tratados com cloroquina ou hidroxicloroquina"
Tweet_2: "2. A Cloroquina e a hidroxicloroquina podem causar efeitos colaterais como redução dos glóbulos brancos, disfunção do fígado, disfunção cardíaca e arritmias, e alterações visuais por danos na retina."

Tweet_1: Do  no  : “sabe qual minha opiniao sobre a cloroquina? Nenhuma. Eu não estudei, não sou médico, não é questão de opinião”.
Tweet_2: Pq as pessoas acham que só os médicos entendem de cloroquina? Quem realmente entende são farmacêuticos, cientistas, bioquímicos e etc. Até o momento, vi poucos defendendo o uso seguro da substância.

Tweet_1: O  divulga orientações para tratamento da Covid-19, onde a Cloroquina pode ser ministrada em casos leves, com recomendação médica e autorização do próprio paciente/família.
Tweet_2: você é um doente mental, se trata ai com cloroquina enquanto os estados unidos tão inventando a porra da vacina.

Tweet_1: O novo protocolo amplia o uso de cloroquina e hidroxicloroquina para casos leves de covid-19 no SUS, contra posicionamentos da Sociedade Brasileira de Infectologia e da Sociedade Brasileira de Imunologia.
Tweet_2: Explicamos nesse fio por que não é possível dizer ainda que a cloroquina é eficaz contra a covid-19

Tweet_1: Porque ele quer que os brasileiros voltem ao trabalho nas ruas, nas empresas, escolas, universidades, independentemente, se for seguro ou não. A cloroquina vai dar uma sensação de segurança, de que tá tudo bem. Ele quer que a economia cresça e o brasileiro mesmo que se foda.
Tweet_2: E quando tudo estiver "bem". Quando tudo voltar ao normal. Muitos vão ver ele como salvador da pátria, como chamam agora. Daí a 5, 10 anos descobriremos os problemas que o uso da cloroquina causou. (Espero muito que não)

Tweet_1: Sob pressão de Bolsonaro, Ministério da Saúde muda protocolo e amplia possibilidade de uso do medicamento também para casos leves, apesar de reconhecer que substância pode agravar quadro clínico.
Tweet_2: Conforme este Soldadestério tudo será autorizado por qualquer soldado, pois não existe mais médico para atrapalhar. Portanto: Cloroquina, estricnina, morfina, Ricina, shiga-toxina, tochina, Cianeto etc. Os caminhões estariam a disposição para levar todo mundo embalado depois. Tok

Tweet_1: TERMO DE CONSENTIMENTO DA CLOROQUINA, OU ROLETA RUSSA.  "Compreendi, portanto, que não existe garantia de resultados positivos, e que o medicamento proposto pode inclusive agravar minha condição clínica...
Tweet_2: ... pois não há estudos demonstrando benefícios clínicos; Estou ciente de que o tratamento com cloroquina ou hidroxicloroquina pode causar os efeitos colaterais descritos acima, e outros menos graves ou menos frequentes, os quais podem levar à disfunção grave de órgãos...

In [119]:
#convertendo para csv
pair_replys_df.to_csv("Cloroquina_pares_reply.csv", index=False, encoding="utf-8")
files.download("Cloroquina_pares_reply.csv")

# **Pares Quote-Tweet**

In [120]:
#filtrando apenas quotes cujos tweets respondidos foram encontrados no dataset
quoteds = df.loc[(df["is_quote"] == True) & (df["quoted_text"].notna())]
quoteds

,tweet_id,user_id_original,text,created_at_original,retweet_count,like_count,is_retweet,retweeter_user_id,retweet_created_at,is_quote,quoted_tweet_id,quoted_user_id,quoted_text,is_reply,reply_to_tweet_id,reply_to_user_id,reply_to_screen_name,reply_text,class
2,1263131993895841793,1087259768,Agora é oficial!!! Vamos de novo: Melhor ter u...,Wed May 20 15:38:29 +0000 2020,934,2934,True,1.254218e+18,Wed May 20 17:48:16 +0000 2020,True,1.263130e+18,1.283729e+08,O divulga orientações para tratamento da Covi...,False,NaN,NaN,NaN,NaN,2
9,1263164662075527170,30931613,"""tem um conhecido meu que é adEvogado e disse ...",Wed May 20 17:48:18 +0000 2020,0,0,False,NaN,NaN,True,1.263106e+18,1.909936e+09,Qual é a cloroquina da sua profissão?,False,NaN,NaN,NaN,NaN,2
21,1263149343026155520,1143196141049323520,Precisamos superar o debate político sobre a c...,Wed May 20 16:47:26 +0000 2020,187,971,True,4.421491e+09,Wed May 20 17:48:21 +0000 2020,True,1.263130e+18,1.283729e+08,"- Ainda não existe comprovação científica, mas...",False,NaN,NaN,NaN,NaN,2
35,1263152814299250688,26991179,“Pior do que ser derrotado é a vergonha de não...,Wed May 20 17:01:13 +0000 2020,1,1,True,1.243009e+18,Wed May 20 17:48:25 +0000 2020,True,1.263130e+18,1.283729e+08,"- Ainda não existe comprovação científica, mas...",False,NaN,NaN,NaN,NaN,2
41,1263164699962638337,1261367834560602117,"""é do levante, tá com Maduro!""",Wed May 20 17:48:27 +0000 2020,0,0,False,NaN,NaN,True,1.263159e+18,7.906800e+05,Cloroquina 'une' Bolsonaro e Maduro em meio à ...,False,NaN,128372940.0,jairbolsonaro,NaN,2
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
67077,1263565972318744578,965400428350464001,A galera da ibope pra esse loco pqp,Thu May 21 20:22:58 +0000 2020,0,0,False,NaN,NaN,True,1.263565e+18,7.906800e+05,"Em entrevista à , Olavo de Carvalho questiona ...",False,NaN,NaN,NaN,NaN,2
67079,1263565974554492941,464767905,formulário socioeconômico,Thu May 21 20:22:58 +0000 2020,0,0,False,NaN,NaN,True,1.263106e+18,1.909936e+09,Qual é a cloroquina da sua profissão?,False,NaN,NaN,NaN,NaN,2
67081,1263565990656426001,162110014,Quero ver quem me diz agora que isso não é lob...,Thu May 21 20:23:02 +0000 2020,0,0,False,NaN,NaN,True,1.263498e+18,7.079932e+07,"Militares já produziram 1,2 milhão de comprimi...",False,NaN,NaN,NaN,NaN,2
67082,1263565991793090561,1251891753973690369,Acho bom e vc ficar quieto. Já já pegam seus p...,Thu May 21 20:23:03 +0000 2020,0,0,False,NaN,NaN,True,1.263454e+18,3.499643e+07,Apresentei um projeto de decreto legislativo p...,False,NaN,NaN,NaN,NaN,2
67083,1263565993818894336,1208380137798017026,O MP tá dormindo ao invés de fazer algo para c...,Thu May 21 20:23:03 +0000 2020,0,0,False,NaN,NaN,True,1.263558e+18,1.158390e+18,O Brasil ganhou mais uma esperança no tratamen...,False,NaN,NaN,NaN,NaN,2

In [121]:
#Gerando pares (por quote)
pair_quote = [] #lista de dicionario que irá armazenar os pares
list_tweet_quote = quoteds["text"].tolist() #transformando tweets do df em lista de tweets
list_quote = quoteds["quoted_text"].tolist() #transformando quote do df em lista de quotes

for i in range(len(list_tweet_quote)):
  pair_quote.append({"tweet_1": list_quote[i], "tweet_2": list_tweet_quote[i] , "Class": 2, "Conflict": np.nan})

pair_quote_df = pd.DataFrame(pair_quote)
pair_quote_df

,tweet_1,tweet_2,Class,Conflict
0,O divulga orientações para tratamento da Covi...,Agora é oficial!!! Vamos de novo: Melhor ter u...,2,NaN
1,Qual é a cloroquina da sua profissão?,"""tem um conhecido meu que é adEvogado e disse ...",2,NaN
2,"- Ainda não existe comprovação científica, mas...",Precisamos superar o debate político sobre a c...,2,NaN
3,"- Ainda não existe comprovação científica, mas...",“Pior do que ser derrotado é a vergonha de não...,2,NaN
4,Cloroquina 'une' Bolsonaro e Maduro em meio à ...,"""é do levante, tá com Maduro!""",2,NaN
...,...,...,...,...
28045,"Em entrevista à , Olavo de Carvalho questiona ...",A galera da ibope pra esse loco pqp,2,NaN
28046,Qual é a cloroquina da sua profissão?,formulário socioeconômico,2,NaN
28047,"Militares já produziram 1,2 milhão de comprimi...",Quero ver quem me diz agora que isso não é lob...,2,NaN
28048,Apresentei um projeto de decreto legislativo p...,Acho bom e vc ficar quieto. Já já pegam seus p...,2,NaN
28049,O Brasil ganhou mais uma esperança no tratamen...,O MP tá dormindo ao invés de fazer algo para c...,2,NaN

In [122]:
for i in range(10):
  #printando na ordem - Quoted tweet - tweet
  print(f'Tweet_1: {pair_quote_df.iloc[i]["tweet_1"]}')
  print(f'Tweet_2: {pair_quote_df.iloc[i]["tweet_2"]}')
  print()

Tweet_1: O  divulga orientações para tratamento da Covid-19, onde a Cloroquina pode ser ministrada em casos leves, com recomendação médica e autorização do próprio paciente/família.
Tweet_2: Agora é oficial!!! Vamos de novo: Melhor ter uma chance usando o remedio que curou o médico do Dória, do q sentar e esperar q o destino lhe dê a oportunidade de ter um tubo enfiado na garganta! Achou ruim? Simples, é só não tomar, mas vc não decide por mim!  #BrasilComBolsonaro

Tweet_1: Qual é a cloroquina da sua profissão?
Tweet_2: "tem um conhecido meu que é adEvogado e disse que pode HC pra prisão por atraso de pensão"

Tweet_1: - Ainda não existe comprovação científica, mas sendo monitorada e usada no Brasil e no mundo. Contudo, estamos em Guerra: “Pior do que ser derrotado é a vergonha de não ter lutado.”  - Deus abençoe o nosso Brasil.
Tweet_2: Precisamos superar o debate político sobre a cloroquina para o bem do país. O Presidente  deseja apenas que o medicamento seja uma opção para os mais pobres, como tem sido para os mais ricos.

Tweet_1: - Ainda não existe comprovação científica, mas sendo monitorada e usada no Brasil e no mundo. Contudo, estamos em Guerra: “Pior do que ser derrotado é a vergonha de não ter lutado.”  - Deus abençoe o nosso Brasil.
Tweet_2: “Pior do que ser derrotado é a vergonha de não ter lutado.

Tweet_1: Cloroquina 'une' Bolsonaro e Maduro em meio à pandemia de coronavírus
Tweet_2: "é do levante, tá com Maduro!"

Tweet_1: Olha aí  , continue lutando pelo bem do povo em várias frentes, equilibrando saúde e economia, é o que precisamos que um presidente faça, tome decisões em tempo. Portugal, não teve efeitos colaterais . A esquerda e os opositores mentem .
Tweet_2: Estão ignorando os efeitos de médio e longo prazo. Foi a mesma coisa com a Talidomida...

Tweet_1: - Ainda não existe comprovação científica, mas sendo monitorada e usada no Brasil e no mundo. Contudo, estamos em Guerra: “Pior do que ser derrotado é a vergonha de não ter lutado.”  - Deus abençoe o nosso Brasil.
Tweet_2: É impossível ter sanidade mental com um presidente desse

Tweet_1: Bolsonaro admite que não há comprovação científica de eficácia da cloroquina contra a covid-19 (via )
Tweet_2: Enfia a “comprovação científica” NO CU!!   Como haveria “comprovação científica” com um vírus que surgiu há pouco tempo??!????   ANTAS!! CANALHAS!

Tweet_1: O Prêmio para concurso de máscaras é um encontro com Michelle Bolsonaro e Damares.  Esse governo é governado por retardados.  Em breve teremos o prêmio de melhor pintura de caixa de cloroquina.  Me avise quando chegarmos ao fundo do poço!
Tweet_2: Essa véia, é a Sílvia Abravanel do governo Bolsonaro!

Tweet_1: - Ainda não existe comprovação científica, mas sendo monitorada e usada no Brasil e no mundo. Contudo, estamos em Guerra: “Pior do que ser derrotado é a vergonha de não ter lutado.”  - Deus abençoe o nosso Brasil.
Tweet_2: Burrice sem fim. Burrice infinita

In [123]:
#convertendo para csv
pair_quote_df.to_csv("Cloroquina_pares_quote.csv", index=False, encoding="utf-8")
files.download("Cloroquina_pares_quote.csv")

In [124]:
#concatenando os datasets parciais:
df_cloroquina = pd.concat([pair_generics_df, pair_replys_df, pair_quote_df], ignore_index=True, axis = 0)
df_cloroquina

,tweet_1,tweet_2,Class,Conflict
0,(Hidroxi)Cloroquina: quem precisar e avaliar (...,Não existe comprovação científica sobre a efic...,0,NaN
1,"E ssa gente querendo cancelar o Lula, só pq el...","acaba de dizer em rede nacional que a Aspen, u...",0,NaN
2,Se a mídia está contra a Cloroquina é porque é...,Tinha que jogar cloroquina nos reservatórios d...,0,NaN
3,Bora dropar cloroquina pra ficar doidão,Assim como o ateu deixa de ser ateu quando pre...,0,NaN
4,CORONAVÍRUS: Ministério da Saúde orienta uso d...,KKKKK CHEIRADOR D PO FALANDO Q USARIA CLOROQUI...,0,NaN
...,...,...,...,...
45102,"Em entrevista à , Olavo de Carvalho questiona ...",A galera da ibope pra esse loco pqp,2,NaN
45103,Qual é a cloroquina da sua profissão?,formulário socioeconômico,2,NaN
45104,"Militares já produziram 1,2 milhão de comprimi...",Quero ver quem me diz agora que isso não é lob...,2,NaN
45105,Apresentei um projeto de decreto legislativo p...,Acho bom e vc ficar quieto. Já já pegam seus p...,2,NaN
45106,O Brasil ganhou mais uma esperança no tratamen...,O MP tá dormindo ao invés de fazer algo para c...,2,NaN

In [125]:
#convertendo para csv
df_cloroquina.to_csv("Cloroquina_pares.csv", index=False, encoding="utf-8")
files.download("Cloroquina_pares.csv")